-- Adminer 4.8.1 MySQL 5.7.37 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `app_my_girl_nl_lyrics`;
CREATE TABLE `app_my_girl_nl_lyrics` (
  `id_music` varchar(20) NOT NULL,
  `lyrics` text NOT NULL,
  `artist` text NOT NULL,
  `album` text NOT NULL,
  `year` tinytext NOT NULL,
  `genre` text NOT NULL,
  FULLTEXT KEY `lyrics` (`lyrics`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

TRUNCATE `app_my_girl_nl_lyrics`;
INSERT INTO `app_my_girl_nl_lyrics` (`id_music`, `lyrics`, `artist`, `album`, `year`, `genre`) VALUES
('86',	'Comment ca va\r\nComme ci comme ci comme ci comme ca\r\nTu ne comprend rien à l\'amour\r\nRestez la nuit, restez toujours\r\nComment ca va\r\nComme ci comme ci comme ci comme ca\r\nTu ne comprend rien à l\'amour\r\nRestez la nuit, restez toujours\r\n\'S Avonds aan de Seine\r\nIn een discotheek\r\nZag ik toen die jongen\r\nDie lachend naar me keek\r\nHij liep plots in mijn richting\r\nDat was toen mijn kans\r\nIk zocht snel naar m\'n woorden\r\nZei toen in m\'n beste Frans\r\nComment ca va\r\nComme ci comme ci comme ci comme ca\r\nTu ne comprend rien à l\'amour\r\nRestez la nuit, restez toujours\r\nComment ca va\r\nComme ci comme ci comme ci comme ca\r\nTu ne comprend rien à l\'amour\r\nRestez la nuit, restez toujours\r\nDenk ik aan die jongen\r\nDan raak ik van de wijs\r\nNachten kan ik dromen\r\nVan die tijd in Parijs\r\nWe waren altijd samen\r\nSamen bij elkaar\r\nMaar lang mocht het niet duren\r\nNu ben ik hier en hij is daar\r\nMisschien dat ik ooit weer terug ga\r\nIk wou maar dat dat kon\r\nDan zeg ik weer die woorden\r\nWaar alles mee begon\r\nComment ca va\r\nComme ci comme ci comme ci comme ca\r\nTu ne comprend rien à l\'amour\r\nRestez la nuit, restez toujours\r\nComment ca va\r\nComme ci comme ci comme ci comme ca\r\nTu ne comprend rien à l\'amour\r\nRestez la nuit, restez toujours',	'Sugarfree',	'Samen Sterk',	'2015',	'Pop'),
('87',	'nie zakręcę wody w łazience\r\nbo mnie potwornie bolą ręce\r\nnie pozbieram rzeczy z podłogi\r\nbo mnie potwornie bolą nogi\r\nnie powiem dziś miłego słowa\r\nbo mnie potwornie boli głowa\r\nnie mam siły na Ojcze Nasz\r\nbo mnie potwornie boli twarz\r\n\r\nale ale\r\ngdy się pojawia coś na ekranie\r\ndostaję turbo doładowanie\r\n\r\nsiema siema\r\nkochanie co za ściema ściema\r\nbył ból i już go nie ma nie ma\r\na taki wielki był\r\nsiema siema\r\nkochanie co za ściema ściema\r\nskąd bierze się ta trema trema\r\nlub nagły nawrót sił\r\n\r\nnie zakręcę wody w łazience…\r\n\r\nhalo halo\r\nręka leniuszka\r\nbuzia kłamczuszka\r\ntakie zmęczone\r\nnie chcą do łóżka\r\n\r\nsiema siema…\r\n\r\ntato za to\r\ntato za to\r\ntato za to ty bądź ze mną szczery\r\nczemu nigdy nie ma czasu na rowery\r\nczemu tak mnie słabo słychać kiedy wołam\r\nczemu mamy tak daleko do kościoła\r\n\r\nniech się ściemnia za oknami\r\nale nigdy między nami\r\n\r\nsiema siema\r\nniech się ściemnia\r\nściema ściema\r\nza oknami\r\nnie ma nie ma\r\nale nigdy\r\nnie ma ściemy nie ma tremy\r\nmiędzy nami',	'Małe TGD',	'Wyspa skarbów',	'2019',	'Pop'),
('88',	'3leish oh oh oh\r\nKifesh oh oh oh oh\r\n\r\nVerse 1 (Salah):\r\nDrab shi dora met mijn boys we gaan dom\r\nIk was op, Mexicano, golden power, caprisun, tla3li dem\r\nKost wat kost, we breken los, dit is raw uncut geen glos\r\nIt ain\'t easy bein\' me daarom doe ik die shit met trots\r\nEy, shoef broer niet alles is Raïbi Jamila\r\nDus ontmantel die scheve blikken en bounce lekker op die handel\r\nEy ey, shta7 shta7 ik onderschat me van de kudde\r\nBen gaan lopen van die tnawie blijf maar hangen in je bubbel, ewa\r\n\r\nPre-hook(Saïd):\r\nTransformeer in een beest\r\nMet mijn mind in een race\r\nOm te zijn waar ik sta het was niet simpel broer\r\nZomer, herfst, winter, lente\r\nInvesteer zonder rente\r\nWant ik weet wat ik wil dus stel geen vragen zovan…\r\n\r\nHook:\r\n3leish oh oh oh\r\nKifesh oh oh oh oh\r\n3leish oh oh oh\r\nKifesh oh oh oh oh\r\nVerse 2 (Saïd):\r\nNieuwe dag, nieuwe test, domme fout, dure les\r\nAf en toe zwaar relax, soms verdwaalt door de stress\r\nIk ben het type dat je ziet als je aan het verliezen bent\r\nTijden zijn hard dus niet klagen omdat ik veranderd ben\r\nGeen tijd voor vragen broer, we doen alles op gevoel\r\nHeb geen tijd voor die tnawie dat is wat ik bedoel\r\nAksht aksht, trainingspaksht, airmax das de stijl\r\nMijn djelaba wordt nooit vuil, beaugosse\r\n\r\nPre-hook(Saïd):\r\nTransformeer in een beest\r\nMet mijn mind in een race\r\nOm te zijn waar ik sta het was niet simpel broer\r\nZomer, hersft, winter, lente\r\nInvesteer zonder rente\r\nWant ik weet wat ik wil dus stel geen vragen zovan…\r\n\r\nHook:\r\n3leish oh oh oh\r\nKifesh oh oh oh oh\r\n3leish oh oh oh\r\nKifesh oh oh oh oh',	'SLM',	'Kifesh',	'2018',	'Hip-Hop/Rap'),
('89',	'Twee, drie, vier\r\nWant hij wilde haar wel brengen, ruim anderhalf uur\r\nDoor regen en door wind, maar liefst één hand aan het stuur\r\nMet nog een hand op haar dijen, want zo ver mocht ie al gaan\r\nEn d\'r is hier niet eens wifi, maar elk bericht komt aan\r\nWant hij was smoorverliefd op haar\r\nEn had nog nooit zoiets gedaan\r\nWant hij zou terug zijn met een uurtje\r\nMoeder\'s fiets mee uit het schuurtje\r\nHij was smoorverliefd op haar\r\nOoh, ooh\r\nTweede klas, havo-vwo\r\nOp m\'n tenen door het huis naar de kamer\r\nMidden in de nacht want misschien werd het m\'n dood\r\nEn onze allergrootste angst was de vader\r\nHandjes boven de lakens, konden nachtenlang praten\r\nVoor het eerst liet een meisje mij volledig in m\'n waarde, echt\r\nHet kon niet naïever en het kon niet puberaler\r\nIk zie hem fietsen over straat\r\nHet voelt als teruggaan in de tijd\r\nWant ik was toen op haar\r\nEn zij was toen op mij, oh\r\nHij was smoorverliefd op haar\r\nEn had nog nooit zoiets gedaan\r\nWant hij zou terug zijn met een uurtje\r\nMoeder\'s fiets mee uit het schuurtje\r\nHij was smoorverliefd op haar\r\nOp haar, alleen op haar, oh-oh\r\nHij wilde haar wel brengen, terug weer anderhalf uur\r\nMaar nu helemaal alleen met nog steeds één hand aan het stuur\r\nWant hij was smoorverliefd op haar\r\nEn had nog nooit zoiets gedaan\r\nWant hij zou terug zijn met een uurtje\r\nNooit de fiets meer in het schuurtje\r\nHij was smoorverliefd op haar\r\nNu zijn ze nooit meer met elkaar\r\nZ\'n telefoon blijft overgaan',	'Snelle',	'Lars',	'2021',	''),
('90',	'Ik was je allang verloren\r\nIk zag je foto in de krant\r\nIk wist niet wat ik hoorde\r\nJe woont weer in de stad\r\nEn niet zo heel veel later zitten wij weer uren bij elkaar\r\nTwee stoelen aan het water en je kijkt me weer hetzelfde aan\r\nBen je nog op reis geweest of heb je het maar laten gaan\r\nHe, weet je wat\r\nIk hoop dat het even duurt\r\nKijk de zon die danst op de ramen\r\n\'T is nog niet eens zomer geweest\r\nWe kunnen overal over praten\r\nMaar soms vertelt de stilte het meest\r\nEn oh, of het niets is\r\nZijn we onderweg naar later en ik\r\nHoop dat het iets is\r\nWat nog blijft als het straks zomer is geweest\r\nWe kijken niet naar de feiten\r\nDoen of je langer blijven kan\r\nHet is niet dat ik spijt heb\r\nMaar heb ik iets gemist, oh\r\nDus sorry dat ik al die tijd geleden hier ben weggegaan\r\nNu kom ik je weer tegen, en we raken niet meer uitgepraat\r\nEn als je me nog even geeft hebben we het weer ingehaald\r\nHe, weet je wat\r\nIk hoop dat het even duurt\r\nKijk de zon die danst op de ramen\r\n\'T is nog niet eens zomer geweest\r\nWe kunnen overal over praten\r\nMaar soms vertelt de stilte het meest\r\nEn oh, of het niets is\r\nZijn we onderweg naar later en ik\r\nHoop dat het iets is\r\nWat nog blijft als het straks zomer is geweest\r\nNa na na na na na na na na\r\nNa na na na na na na na\r\nNa na na na na na na na na\r\nNa na na na na na na na\r\nEn oh, of het niets is\r\nZijn we onderweg naar later en ik\r\nHoop dat het iets is\r\nWat nog blijft als het straks zomer is geweest\r\nNa na na na na na na na na\r\nNa na na na na na na na (als het zomer is geweest)\r\nNa na na na na na na na na\r\nNa na na na na na na na\r\nNa na na na na na na na na\r\nNa na na na na na na na',	'Suzan',	'Onderweg Naar Later',	'2021',	''),
('91',	'Ooh, yeah\r\nAh yeah, whoo\r\nSexy als ik dans\r\nHm-mm, yeah\r\nAh!\r\nWeet je wat het is? Ik heb geen goeie moves\r\nMaar zie je niet dat ik, precies weet wat ik doe?\r\nEn ze kan het niet laten (Nee), ze kan het niet laten\r\nYeah, yeah (Ah)\r\nWeet je wat het is? Zij komt naar me toe\r\nZe vraagt me: \"Ga je lekker? Wat ben je nou aan \'t doen?\"\r\nEn ik kan het niet laten (Nee), ik kan het niet laten\r\nIk zeg: \"Weet je wat het is, babe? Ik voel me sexy als ik dans\"\r\nWho-o-o-oh oo-oh (Yeah), oo-o-oh\r\nSexy als ik dans, eeh, ehe-e-ey\r\nIk voel me sexy als ik dans\r\nWho-o-o-oh oo-oh (Yeah, huh)\r\nIk voel me sexy als ik dans, eeh, ehe-e-ey\r\nOeh!\r\nWeet je wat het is? Ik heb ze al gehoord\r\nAl die goeie tips, maar ze, maar ze werkten nooit\r\nEn toch kan je het niet laten (Nee), je kan het niet laten\r\nAw yeah (Ah)\r\nErgens in haar blik, zie ik dat er iets\r\nAh, iets veranderd is, en ik geloof m\'n ogen niet\r\nZe kan het niet laten, ze springt op de tafel\r\nDaar gaat ze, daar gaat ze\r\nZe kan het niet laten, ze springt op de tafel\r\nEn daar gaat ze, yeah\r\nZe zegt: \"Weet je wat het is, babe? Ik voel me sexy als ik dans\"\r\nWho-o-o-oh oo-oh (Yeah), oo-o-oh\r\nSexy als ik dans, eeh, ehe-e-ey\r\nIk voel me sexy als ik dans\r\nWho-o-o-oh oo-oh (Yeah, huh)\r\nIk voel me sexy als ik dans, eeh, ehe-e-ey\r\nSteek ik m\'n hand op\r\nGaan m\'n voeten zomaar de verkeerde kant op\r\n(Als jij danst)\r\nGooi jij je haar los\r\nSwingen je heupen zo lekker dat het een gevaar wordt\r\nSteek ik m\'n hand op\r\nGaan m\'n voeten zomaar de verkeerde kant op\r\n(Als jij danst)\r\nGooi jij je haar los\r\nSwingen je heupen zo lekker dat het een gevaar wordt\r\nIk zeg: \"Weet je wat het is, babe? Ik voel me sexy als ik dans\"\r\nWho-o-o-oh oo-oh (Yeah), oo-o-oh\r\nSexy als ik dans, eeh, ehe-e-ey\r\nIk voel me sexy als ik dans\r\nWho-o-o-oh oo-oh (Ooh, ik voel me sexy als ik, uh)\r\nIk voel me sexy als ik dans, eeh, ehe-e-ey\r\nIk voel me sexy als ik dans (Who-o-o)\r\nSteek ik m\'n hand op (Oh oo-oh)\r\nGaan m\'n voeten zomaar de verkeerde kant op (Oo-o-oh)\r\nSexy als ik dans\r\nGooi jij je haar los (Eeh)\r\nSwingen je heupen zo lekker dat het een gevaar wordt (Ehe-e-ey)\r\nIk voel me sexy als ik dans (Who-o-o-oh oo-oh)\r\nSteek ik m\'n hand op (Yeah, huh)\r\nGaan m\'n voeten zomaar de verkeerde kant op\r\nIk voel me sexy als ik dans\r\nGooi jij je haar los (Eeh)\r\nSwingen je heupen zo lekker dat het een gevaar wordt (Ehe-e-ey)\r\nSexy als ik dans',	'Nielson',	'Weet Je Wat Het Is',	'2016',	'Pop'),
('92',	'[Intro]\r\nChwile słodko słodkie, ey, słodko słodkie, ey\r\nSłodko słodkie, chwile słodko słodkie\r\nZ tobą jeszcze słodsze, ey, jeszcze słodsze, ey\r\nJeszcze słodsze, są jeszcze słodsze\r\n\r\n[Zwrotka 1]\r\nDeszcz za oknem kapie kap, kap\r\nZe mną słodkie chwile łap, łap\r\nDawniej trawka, park i ławka\r\nDziś wstaję rano i jazda\r\nSerce puka jak pukawka\r\nPopularność szklana pułapka\r\nKłapią dzioby jakby kaczka\r\nNie mam czasu na bla, bla, bla\r\nLudzie mówią to \"lucky punch\"\r\nMoja praca, ty śmiej się, baw\r\nW twoim mieście gramy gruby bal\r\nPlener, kluby, moja muzyka, moja muzyka\r\n\r\n[Refren]\r\nTo życie ja sobie wyśniłem je\r\nSwe oczy zamykam i płynę gdzieś\r\nPrzez chmury, dzień, noc, słodkie chwile te\r\nDaj dłoń, postaw krok, popłyniemy w rejs\r\nGdy życie jest gorzkie pamiętaj, że\r\nTo życie ja sobie wyśniłem je\r\nSwe oczy zamykaj i popłyń gdzieś\r\nPrzez chmury, dzień, noc, słodkie chwile te\r\nTo życie ja sobie wyśniłem je\r\nSwe oczy zamykam i płynę gdzieś\r\nPrzez chmury, dzień, noc, słodkie chwile te\r\nDaj dłoń, postaw krok, popłyniemy w rejs\r\nGdy życie jest gorzkie pamiętaj że\r\nTo życie ja sobie wyśniłem je\r\nSwe oczy zamykaj i popłyń gdzieś\r\nPrzez chmury, dzień, noc, słodkie chwile te\r\n\r\n[Bridge]\r\nChwile słodko słodkie, ey, słodko słodkie, ey\r\nSłodko słodkie, chwile słodko słodkie\r\nZ tobą jeszcze słodsze, ey, jeszcze słodsze, ey\r\nJeszcze słodsze, są jeszcze słodsze\r\n\r\n[Zwrotka 2]\r\nWczoraj, jutro nieważne\r\nTeraz powiedz mi prawdę\r\nCzy chcesz jak ja poważnie\r\nPopatrz w oczy, nie kłam mnie\r\nPłyńmy w rejs tym statkiem\r\nTy jesteś moim skarbem\r\nZłożyłem układankę\r\nTo było proste, nie łatwe\r\nMała wszystko załatwię\r\nOddaj siebie, ja dam też\r\nŚciągniemy każdą maskę\r\nŻyjmy teraz naprawdę\r\n\r\n[Refren]\r\nTo życie ja sobie wyśniłem je\r\nSwe oczy zamykam i płynę gdzieś\r\nPrzez chmury, dzień, noc, słodkie chwile te\r\nDaj dłoń, postaw krok, popłyniemy w rejs\r\nGdy życie jest gorzkie pamiętaj że\r\nTo życie ja sobie wyśniłem je\r\nSwe oczy zamykaj i popłyń gdzieś\r\nPrzez chmury, dzień, noc, słodkie chwile te',	'Wac Toja',	'Cały Lokal Skacze',	'2021',	'');

-- 2022-03-17 15:40:59
