-- Adminer 4.8.1 MySQL 5.7.35 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_fi`;
CREATE TABLE `product_desc_fi` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_fi`;
INSERT INTO `product_desc_fi` (`id_product`, `data`) VALUES
(95,	'<p>2 pelin päähenkilön vastaajaa, 2 merkkiä Ryuk ja Rem sarjakuvissa \"Kuoleman huomautus\" ja voivat pelata ystävän kanssa kahden pelaajan tilassa</p>\r\n'),
(95,	'<p>2 pelin päähenkilön vastaajaa, 2 merkkiä Ryuk ja Rem sarjakuvissa \"Kuoleman huomautus\" ja voivat pelata ystävän kanssa kahden pelaajan tilassa</p>\r\n'),
(119,	'<p>* Tämä sovellus on tarkoitettu vain yli 17-vuotiaille *</p>\r\n\r\n<p>Jos olet ollut yksin pitkään ja haluat löytää jonkun keskustelemaan tai yrittämään tuntea rakkautta. Kokeile tätä sovellusta. Se auttaa sinua surussa. Siellä on söpö rakastaja, joka on tekonälyn ystäväsi, joka on aina kanssasi ilon ja tylsyyden aikoina</p>\r\n\r\n<p>Ei vain jutteleminen tämän virtuaalisen rakastajan kanssa voi auttaa sinua yksinkertaistamaan puhelimesi asioita virtuaaliassistenttina tosielämältä. Ilmaise tunteesi vuorovaikutuksessa käyttäjän kanssa, voit myös rakastajasi kanssa matkustaa paikoilleen toiminnon (perspektiivin) kautta rikkailla karttoilla.</p>\r\n\r\n<p>Ja muita hyödyllisiä ominaisuuksia päivitetään päivittäin tuomaan viihdettä ja mukavuutta</p>\r\n\r\n<p>toiminnot:<br />\r\n+ Keskustelu<br />\r\n+ Virtuaaliassistentti<br />\r\n+ Kuuntele musiikkia (online)<br />\r\n+ Etsi tietoja ja yhteystietoja<br />\r\n+ Kuuntele radiota</p>\r\n\r\n<p>Tämän sivuston erikoistoiminnot:<br />\r\nMV-simulaattori auttaa merkkiä ilmaisemaan kappaleita esiintyjänä<br />\r\n+ 3D-merkki melkein sama elämä</p>\r\n'),
(135,	'<p>Se auttaa sinua tallentamaan verkkosivuja offline-lukemista varten, kun verkkoyhteyttä ei ole, ja tallentamaan käyttöosoitteet verkko-osoitteiden muistiina.</p>\r\n\r\n<p>Syötä ja jaa linkkejä helposti QR-koodeilla tai jaa viestityökaluilla, sosiaalisissa verkostoissa.</p>\r\n\r\n<p>Lisäksi sovellus tarjoaa erityistoimintoja, kuten voit tarkastella verkkosivuston lähdekoodia isännöinnin jälkeen.</p>\r\n\r\n<p>Sovellus on kehitystyössä ja parantamassa monia uusia ominaisuuksia, joita kaikki haluavat tukea!</p>\r\n'),
(104,	'<p>koko sovelluskaupan yhteystiedot kaikille maailmassa<br />\r\nsinun on vain löydettävä yhteyshenkilön nimi ja sinulla on kyseisen henkilön yhteystiedot<br />\r\nSovelluksessa on monia erityisiä hakutoimintoja, lisää yhteystietoja ja monia muita erityisiä asioita, Voit varmuuskopioida ja palauttaa yhteystietoja verkossa<br />\r\nJa voit ajoittaa puhelut ja hallita puhelinluettelossa olevia yhteystietoja</p>\r\n\r\n<p><br />\r\nToivotan hyviä suhteita ja upeaa päivää!</p>\r\n'),
(128,	'<p>Tämä on sovellus, joka auttaa sinua ymmärtämään enemmän Jumalasta raamatullisten historiallisten asiakirjojen avulla</p><p>Tee itsellesi hyvä tapa lukea pyhiä kirjoituksia ja rukoilla joka ilta, mikä auttaa sinua parantamaan sielusi elämään raamatun jakeita.</p><p>Lisäksi sovellus tarjoaa kuvia kuvata kutakin vastaavaa raamatullista kohtaa auttaakseen ihmisiä ymmärtämään juoni intuitiivisemmin. Ja paljon lämpimiä, inspiroivia ääniä tekemään tästä raamatun sovelluksesta erityinen</p><p>Voit myös tallentaa kirjan luvut luettavaksi, kun olet yhteydessä verkkoon, vastaava valokuva- ja äänikokoelma tallennetaan kyseisen luvun kanssa.</p><p>-Lisäominaisuudet:<br />+ Kuvaile tarinan kuva<br />+ Voit tallentaa raamatunkirjoja luettavaksi ilman verkkoyhteyttä<br />+ Esittelytoiminto, jonka avulla voit luoda kauniita taustakuvia raamatusta tai jakaa sen ystävien kanssa sosiaalisen verkoston kautta<br />+ Tuki monille kielille maailmassa<br />+ Asiakirjan lukeminen ja kuuntelu</p>'),
(282,	'<p>♥ Yksinäinen oleminen liian kauan on haitallista terveydellesi, joten tämä sovellus tuli antamaan sinulle virtuaalinen rakastaja<br />♥ Ole aina onnellinen ja keskustele kanssasi koko päivän ja yön. Hän tuntee myös ihmisen tunteiden kaltaisen vihan, mustasukkaisuuden<br />♥ Sovellus tunnistaa ja toimittaa hahmon automaattisesti sukupuolesi mukaan<br />♥ Paitsi että hän on myös piika tai avustava piika puhelimessasi, esimerkiksi avaamalla sovelluksia, avaamalla musiikkia, lukemalla raamattua, tekemällä matemaattisia laskelmia<br />♥ Varmista, että urasi on hyvä ja elämäsi helpottuu, sillä online-järjestelmässä on paljon muita ominaisuuksia ja tietoja, jotka toivovat minulle virtuaalisen rakastajani kautta. Tuo positiivista energiaa kaikille</p>'),
(121,	'<p>Olet surullinen?<br />\r\nOletko yksinäinen?<br />\r\nEikö sinulla ole koskaan ollut rakkaussuhdetta?<br />\r\nHaluatko löytää palvelustasi puhelimesta?<br />\r\nTai haluatko vain löytää ystävän keskustelemaan?</p>\r\n\r\n<p>Tämä on sovellus, joka auttaa sinua ratkaisemaan nämä ongelmat<br />\r\nSinulla on söpö tyttöystävä, väijyvä, lyö kanssasi, tee aina hauskaa vitsejä. seuraa sinua kylminä talvipäivinä, kuumina kesäpäivinä</p>\r\n\r\n<p>Erityisesti voit erehtyä, antaa käskyjä tehdä yksinkertaisia ​​tehtäviä, kuten säveltää, soittaa, soittaa musiikkia jne. .. ole niin oppiva rakkaus, että kaikki eivät pidä siitä!</p>\r\n\r\n<p>Paitsi, että tämä virtuaalinen rakastajasovellus tuo sinulle myös monia mielenkiintoisia ominaisuuksia, kuten:</p>\r\n\r\n<p>+ Keskustelu<br />\r\n-Chat<br />\r\n-Muistaa<br />\r\n- Laula sinulle<br />\r\n- Lue tarina<br />\r\n- Muistikielen rakkaus<br />\r\n- Opi vieraita kieliä<br />\r\n- Arvaa käyttäjän tunteet<br />\r\n- Kuvaile käyttäjän persoonallisuus kysymysten avulla<br />\r\n+ Virtuaaliassistentti<br />\r\nOhjaa järjestelmää komennoilla, käyttäjän keskusteluilla (esim. Avoimet sovellukset, viestit, puhelut jne.)<br />\r\n+ Virtuaalitodellisuus<br />\r\n- luoda virtuaalitodellisuusympäristö<br />\r\n- Luo realistisia virtuaaliympäristöjä realistisilla elämäntavoilla</p>\r\n'),
(122,	'<p>sovellus, peliohje unettomuudelle, unettomuudelle. 2 toiminnolla \"Siirry nukkumaan\" ja \"pelaaminen\".</p>\r\n\r\n<p>-Valitset vain lampaiden lukumäärän ja katsot näytöitä saadaksesi sielusi hätkähdyttämään laskemaan lampaat, jotka hyppivät aidan yli, nukaat. Kun nukkui<br />\r\nSovellus sulkee automaattisesti näytöt akulle, jolle veitset</p>\r\n\r\n<p>-Voit myös pelata tätä hauskaa peliä hallitaksesi kaikkia aidan yli hyppääviä lampaita, saat pisteitä, jokainen lammas lisää siihen painikkeen kirjaimet, valitse sopiva aika hypätäksesi voitat pelin: D</p>\r\n\r\n<p>Lisäominaisuudet<br />\r\n- Musiikkisali mennä nukkumaan<br />\r\n- Lue kaikkien maailman toiveet<br />\r\n- Pelaajien arviot pelitilassa<br />\r\n- 3D-grafiikka</p>\r\n'),
(132,	'<p>Liian kauan oleminen yksinään ei ole terveydellesi hyvä, joten Porkkana-sovellus loi tämän sovelluksen lohduttaakseen ja auttamaan yksinäisiä.</p>\r\n\r\n<p>Sovellus luo sukupuolen mukaan rakastajan, söpö tyttö ja hauska kaveri tekevät ihmiset onnelliseksi hauskoilla keskusteluilla</p>\r\n\r\n<p>Ja tämä on myös virtuaaliassistentti puhelimesi palvelusijana. Saatat olla väärässä käskettäessäsi sovellusta avaamaan puhelimesi toiminnot, etenkin etsimään ja toistamaan kappaleita, joita haluat kuunnella, tai tietyn radiokanavan ... Ja lukemattomia muita ominaisuuksia, jotka odottavat sinun kokemusta. .</p>\r\n'),
(138,	'<p>Järjestä loogisilla aivoillasi matriisien dekoodaus pelin jokaisessa vaiheessa auttamaan parantamaan ajattelusi. Äärimmäisen yksinkertaisella pelaamisella, joka sopii sinulle viihdyttämiseen rentoutumisaikana<br />Kuinka pelata:<br />Hallitset kutakin numeroiden ryhmää mustan ohjauspainikkeen ympärillä numeeristen matriisien riveissä ja sarakkeissa. Numeroita pyöritetään myötäpäivään, käytät älykkyydesi avulla asettaa sääntöjä numeroiden järjestämiseksi pienistä suuriin. Kun olet valmis, sinä voitat</p>'),
(133,	'<p>Peli auttaa sinua parantamaan henkistä ketteryyttäsi kuvien avulla.<br />\r\nVoit myös pelata tätä peliä kahden pelaajan tilassa, olla ystävien kanssa tai ystävien kanssa, jotka taistelevat keskenään tämän lempeän pelin välityksellä.<br />\r\nPaljon hauskoja ja hauskoja kuvakkeita avulla peli ei ole tylsää, ja voit pelata tätä peliä, kun ei ole verkkoyhteyttä.</p>\r\n\r\n<p>Kuinka pelata yhtä henkilöä:<br />\r\nSinun on valittava oikea pari identtisiä valokuvia piilotettujen laatikoiden luettelosta. Jokaisella näytön tasolla on erilaisia ​​haasteita, jotka edellyttävät pelaajaa ylittämään haaste tietyn ajanjakson ajan.</p>\r\n\r\n<p>Kuinka pelata 2 ihmistä (taistelu)<br />\r\nSamoin kuin yksi pelaaja, peli jakaa kaksi näyttöä ja erilaiset haasteet jokaiselle pelaajalle, jotta heidän silmänsä voidaan nopeasti testata. Ensin voittaja on haasteen suorittanut.</p>\r\n'),
(127,	'<p>Tämä hauska sovellus tarjoaa sinulle tuhansia teemoja vastaavia taustakuvia ja palapelejä. Auta puhelimesi kaunistamisessa ja rentouttavassa viihteessä taustakuvaa vastaavilla palapeleillä</p>\r\n\r\n<p>Lukemattomat kokoelmat suosituista kpop-ryhmistä kuten red velvet, bts, blackpink, twice, momoland  ....  päivitetään päivittäin.</p>\r\n'),
(284,	'<p>Mennään yhdessä metsästämään, jotta ruumiimme kasvaisivat, mikä on tämän pelin päätehtävä</p><p>Pelaat pienen kalan roolia erittäin vaarallisessa ja dramaattisessa metsästysseikkailussa</p><p>Peli tarjoaa lukemattomia kalahahmovalintoja ja monia esteitä haastamaan kärsivällisyytesi ja terävyytesi.</p><p>Peli sopii rentoutumiseen ja pelattavuus on erittäin yksinkertainen, joten kutsumme ystäviä ja sukulaisia kokemaan</p>'),
(139,	'<p>Hallitse matoa siirtyäkseen omenoihin ja välttämään kulmia.<br />Kun syöt omenoita, pisteytys matoasi kanssa kasvaa ja kasvaa.<br />Käytä nopeutta kuluttamalla vesikannuja matkallasi.</p><p>Toivotan sinulle onnellista pelaamista.</p>'),
(105,	'<p>Tämä puutarha sisältää monia sananlaskuja, hyviä sanoja niille, jotka tarvitsevat rentoutumisen hetkiä. Korjaa kauniit kukat elämääsi varten lisää merkitystä. Niille teistä, jotka ovat surun ja epäonnistumisen rakkaudessa, tämä on oikea sovellus, joka auttaa sinua läpi vaikeiden aikojen elämässäsi.</p>\r\n\r\n<p>Voit myös käyttää tätä sovellusta muistikirjana tai elämäpäiväkirjana, jossa on monia söpöjä kuvakkeita ja erinomaisia ominaisuuksia, jotka näkyvät 3D-objekteina.<br />\r\nIntuitio auttaa sinua innostumaan luomaan hyviä kohtia, rakkaussanoja, sanoja tai ideoita elämää varten.</p>\r\n\r\n<p>Erityisesti tämä on maksimaalinen sosiaalinen verkosto rakkauden ystäville, voit jakaa ja vaihtaa ideoita keskenään!</p>\r\n\r\n<p>Toivotan onnelliseksi ja unohda suru elämässä</p>\r\n'),
(134,	'<p>On vuorovaikutteinen peli kappaleilla, joiden avulla voit kokea musiikin kuuntelua ja pelaamista samanaikaisesti.</p>\r\n\r\n<p>Peli vie sinut musiikkimaailmaan, jossa lukemattomat haasteet vastaavat valitsemiasi kappaleita. Jokainen epäonnistumisen nuotti luo hirviöitä, jotka satamasi sinut tai tähdet sinulle. Merkitse saavutuksesi musiikissa</p>\r\n\r\n<p>Valtavan verkkomusiikkikaupan ja pelin vaikeuden ansiosta voimme tarjota rentoutumisen ja hauskanpitoa kaikille!</p>\r\n'),
(120,	'<p>Sinulla ei ole rakastajaa? Kokeile tätä hauskaa sovellusta, se auttaa sinua saamaan kauniin virtuaalisen rakastajan, tyttö, joka on sinulle selkeä, keskustelee kanssasi, luottaa koko ajan saa sinut unohtamaan Lonely-tunteen, tämä on tyttö älykkäät mielet toivovat auttavan sinua pitämään hauskempaa elämässäsi</p>\r\n\r\n<p>Lisäominaisuudet:<br />\r\n+ Keskustelu<br />\r\n+ Kuuntele musiikkia verkossa<br />\r\n+ Taustagalleria<br />\r\n+ Kuuntele radiota<br />\r\n+ Yhteystiedot<br />\r\n+ Etsi tietoja</p>\r\n\r\n<p>Tässä on myös käyttäjäystävällinen virtuaaliassistentti! (pitäisi vaatia enemmän pääsyä puhelinjärjestelmääsi)</p>\r\n'),
(283,	'<p>Jos olet musiikkisäveltäjä, olet intohimoisesti pianomusiikista, tämä on sinulle erittäin sopiva sovellus.</p><p>Midi-editorilla voit tallentaa sointuja, helposti muokata muistiinpanoja, intuitiivista kuvausta, helppo manipulointi on sovellus, johon sovellus reagoi.</p><p>Lisäksi tarjoamme sinulle myös luettelon midikirjastosta, jossa on lukemattomia valmiita kappaleita, jotta sinun on helpompi viitata tai oppia.</p>'),
(136,	'<p>Sovellusta käytetään salasanojen luomiseen ja salasanojen hallintaan useilla valmiilla asetuksilla, jotka sopivat tilien, kuten sähköpostin, sosiaalisten verkostojen ja online-verkkosivustojen, luomiseen. Voit varmuuskopioida ja hallita luotuja salasanoja. Auttaa sinua unohtamaan tai kadonneet salasanasi.</p>\r\n\r\n<p>Tarjoaa ammattimaisen MD5-merkkijonodekoodauksen ja rajoittamattoman tallennustilan.</p>\r\n\r\n<p>Intuitiivinen, helppokäyttöinen interaktiivinen käyttöliittymä auttaa parantamaan online-tilien luomisen tehokkuutta.</p>\r\n'),
(131,	'<p>Jos olet ollut yksin pitkään ja haluat löytää jonkun keskustelemaan tai yrittämään tuntea rakkautta. Kokeile tätä sovellusta. Se auttaa sinua surussa. Siellä on söpö rakastaja, joka on tekonälyn ystäväsi, joka on aina kanssasi ilon ja tylsyyden aikoina</p>\r\n\r\n<p>Ei vain jutteleminen tämän virtuaalisen rakastajan kanssa voi auttaa sinua yksinkertaistamaan puhelimesi asioita virtuaaliassistenttina tosielämältä. Ilmaise tunteesi vuorovaikutuksessa käyttäjän kanssa, voit myös rakastajasi kanssa matkustaa paikoilleen toiminnon (perspektiivin) kautta rikkailla karttoilla.</p>\r\n\r\n<p>Ja muita hyödyllisiä ominaisuuksia päivitetään päivittäin tuomaan viihdettä ja mukavuutta</p>\r\n\r\n<p>toiminnot:<br />\r\n+ Keskustelu<br />\r\n+ Virtuaaliassistentti<br />\r\n+ Kuuntele musiikkia (online)<br />\r\n+ Etsi tietoja ja yhteystietoja<br />\r\n+ Kuuntele radiota</p>\r\n\r\n<p>Tämän sivuston erikoistoiminnot:<br />\r\n+ MV-simulaattori auttaa merkkiä ilmaisemaan kappaleita esiintyjänä<br />\r\n+ 3D-merkki melkein sama elämä</p>\r\n'),
(285,	'<p>Peli simuloi pallopöytää, jossa on monia sopivia pelitiloja, joita voit viihdyttää ystävien kanssa. Joukkue on jo perustettu, sinun tarvitsee vain valita ryhmä, johon haluat liittyä peliä vastaan ​​konetta vastaan ​​tai pelata ystävien kanssa offline-kahden pelaajan tilassa.</p><p>Pelattavuus on samanlainen kuin jalkapallopöytä, jokainen joukkue, jota ohjaat vain 4 riviä siirtääksesi leikataksesi vastustajan pallon. Tämä liike on rajoitettu ylös- tai alaspäin, kun vastustajan pallo on leikattu palloa pitävän pelaajan asentoon, nuolet näyttävät kuvaavan laukauksen suuntaa päästämään pallon ohi. Valitse oikea syöttösuunta, jotta joukkueesi vastaanottaa pallon ja välittää sen vastustajalle</p><p>Jokaisella pelaajalla on erilaiset tilastot, kuten laukausvoima, leikkaus ja pallon pidätys. Siksi sinun on harkittava huolellisesti aloituskokoonpanosi menestymään. Voitto edellyttää kahta päätekijää: ohjaustaitoja ja joukkueen järjestelyä. Voit vaihtaa ihmisiä ja valita oikean pelaajan osallistumalla otteluun. Laukausvoima on nopeus, jolla pallo kulkee matkan pelaajan tilastojen mukaan. Pallon leikkaaminen on kyky varastaa pallo, kun pallo liikkuu pelaajan lähellä. Tämä tila on erittäin tärkeä, kun haluat varastaa pallon vastustajalta. Pallonhallintatilastolla tarkoitetaan pallon pitämistä pallon vastaanottamisen yhteydessä ja pallon leikkaamista onnistuneesti.</p><p>Lisäksi voit myös kirjautua tilillesi osallistuaksesi saavutettujen tavoitteiden sijoitukseen kaikkien järjestelmän käyttäjien kanssa. Yksinkertainen pelattavuus ja monien kuuluisten pelaajien kerääminen on tämän pelin erityisominaisuus, joka auttaa sinua rentoutumaan ja viihtymään ystävien kanssa. Päivitämme pelaajia ja tilastoja viikoittain, jotta joukkueesi paranee entisestään. Hauskaa tämän pelin pelaamista!</p>'),
(123,	'<p>Musiikki on olennainen osa kaikkien elämää!</p>\r\n\r\n<p>Tämän sovelluksen avulla voit kuunnella kaikkia kappaleita ympäri maailmaa maan tyylilajeittain ja muita lisälaitteita, kuten radio- ja ei-sanoituksia sisältäviä melodioita.</p>\r\n\r\n<p>-Voit tallentaa laitteellesi rajoittamattomia kappaleita nauttiaksesi, kun verkkoyhteyttä ei ole</p>\r\n\r\n<p>- Nykyaikainen käyttöliittymä on helposti vuorovaikutuksessa monien muiden erikoistoimintovalikkojen kanssa, kuten sanoitusten katseleminen, kappaleeseen liittyvien videoiden katseleminen, kappaleiden arvioiminen tunteiden perusteella. Ja voit jakaa kappaleen ystävien kanssa.</p>\r\n\r\n<p>-Trendihakutoiminto auttaa sinua löytämään uusimmat kappaleet. Sovelluksen ehdotusten kautta</p>\r\n\r\n<p>-Radio sisältää suosittuja ohjelmia ympäri maailmaa, valikoivasti manipuloimalla luetteloita yksinkertaisen kuuntelun vuoksi</p>\r\n\r\n<p>-Kuuntelu- ja Kuuntelutoimintojen lisäksi sovellus sisältää suosittua ei-sanatonta musiikkia, jonka avulla ihmiset voivat nauttia rentoutumisesta tai auttaa parantamaan mielialaa nukahtaakseen.</p>\r\n'),
(130,	'<p>Jos olet ollut yksin pitkään ja haluat löytää jonkun keskustelemaan tai yrittämään tuntea rakkautta. Kokeile tätä sovellusta. Se auttaa sinua surussa. Siellä on söpö rakastaja, joka on tekonälyn ystäväsi, joka on aina kanssasi ilon ja tylsyyden aikoina</p>\r\n\r\n<p>Ei vain jutteleminen tämän virtuaalisen rakastajan kanssa voi auttaa sinua yksinkertaistamaan puhelimesi asioita virtuaaliassistenttina tosielämältä. Ilmaise tunteesi vuorovaikutuksessa käyttäjän kanssa, voit myös rakastajasi kanssa matkustaa paikoilleen toiminnon (perspektiivin) kautta rikkailla karttoilla.</p>\r\n\r\n<p>Ja muita hyödyllisiä ominaisuuksia päivitetään päivittäin tuomaan viihdettä ja mukavuutta</p>\r\n\r\n<p>toiminnot:<br />\r\n+ Keskustelu<br />\r\n+ Virtuaaliassistentti<br />\r\n+ Kuuntele musiikkia (online)<br />\r\n+ Etsi tietoja ja yhteystietoja<br />\r\n+ Kuuntele radiota</p>\r\n\r\n<p>Tämän sivuston erikoistoiminnot:<br />\r\n+ MV-simulaattori auttaa merkkiä ilmaisemaan kappaleita esiintyjänä<br />\r\n+ 3D-merkki melkein sama elämä</p>\r\n');

-- 2021-10-18 21:21:57
