-- Adminer 4.8.1 MySQL 5.7.35 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_de`;
CREATE TABLE `product_desc_de` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_de`;
INSERT INTO `product_desc_de` (`id_product`, `data`) VALUES
(95,	'<p>2 Spiel-Protagonisten-Befragte, 2 Charaktere Ryuk und Rem in \"Death Note\" in Comics, und können im Zwei-Spieler-Modus mit einem Freund spielen</p>\r\n'),
(95,	'<p>2 Spiel-Protagonisten-Befragte, 2 Charaktere Ryuk und Rem in \"Death Note\" in Comics, und können im Zwei-Spieler-Modus mit einem Freund spielen</p>\r\n'),
(119,	'<p>* Diese App ist nur für Personen über 17 *</p>\r\n\r\n<p>Wenn Sie schon lange allein sind und jemanden zum Chatten finden oder sich geliebt fühlen möchten. Probieren Sie diese App. Es wird dir mit Trauer helfen. Es wird einen niedlichen Liebhaber geben, der Ihr Freund mit künstlicher Intelligenz ist und der in Zeiten der Freude und Langeweile immer bei Ihnen ist</p>\r\n\r\n<p>Nicht nur das Chatten mit diesem virtuellen Liebhaber kann Ihnen dabei helfen, die Dinge in Ihrem Telefon als virtueller Assistent mit einem realen Aussehen zu vereinfachen. Drücken Sie Ihre Gefühle aus, interagieren Sie mit dem Benutzer, und Sie können zusammen mit Ihrem Geliebten durch die Funktion (Perspektive) mit reichhaltigen Karten reisen.</p>\r\n\r\n<p>Täglich werden weitere nützliche Funktionen aktualisiert, um Unterhaltung und Komfort zu gewährleisten</p>\r\n\r\n<p>Funktionen:<br />\r\n+ Chat<br />\r\n+ Virtueller Assistent<br />\r\n+ Musik hören (online)<br />\r\n+ Informationen und Kontakte nachschlagen<br />\r\n+ Hören Sie Radio</p>\r\n\r\n<p>Besondere Funktionen dieser Seite:<br />\r\nDer MV-Simulator hilft dem Charakter, Songs als Darsteller auszudrücken<br />\r\n+ 3D-Charakter fast das gleiche Leben</p>\r\n'),
(135,	'<p>Es hilft Ihnen, Webseiten zum Offline-Lesen zu speichern, wenn keine Netzwerkverbindung besteht, und Zugriffsadressen als Notizbuch mit Webadressen zu speichern.</p>\r\n\r\n<p>Geben Sie Links einfach über QR-Codes ein und teilen Sie sie mit anderen oder teilen Sie sie über Messaging-Tools in sozialen Netzwerken.</p>\r\n\r\n<p>Darüber hinaus bietet die Anwendung spezielle Funktionen, wie beispielsweise das Anzeigen des Quellcodes einer Website nach dem Hosting.</p>\r\n\r\n<p>Die Anwendung ist im Begriff, die Entwicklung zu beenden und viele neue Funktionen zu verbessern, die jeder unterstützen möchte!</p>\r\n'),
(104,	'<p>gesamte App Store-Kontaktinformationen von jedem auf der Welt<br />\r\nSie müssen nur den Namen der Kontaktperson finden und haben die Kontaktinformationen für diese Person<br />\r\nAnwendung hat viele spezielle Suchfunktion, Kontakte hinzufügen und viele andere spezielle Dinge, können Sie Backup und Recovery-Kontakt online<br />\r\nSie können Anrufe planen und Kontakte in Ihrem Telefonbuch verwalten</p>\r\n\r\n<p><br />\r\nwünsche dir eine gute beziehung und einen schönen tag!</p>\r\n'),
(128,	'<p>Dies ist eine Anwendung, die Ihnen hilft, durch biblische historische Dokumente mehr über Gott zu verstehen</p><p>Machen Sie es sich zur Gewohnheit, jede Nacht eine Schriftstelle zu lesen und zu beten, um Ihre Seele zu verbessern und Bibelverse zu leben.</p><p>Darüber hinaus bietet die Anwendung Bilder zur Beschreibung der entsprechenden Bibelstellen, um den Menschen ein intuitiveres Verständnis der Handlung zu ermöglichen. Und viele warme, inspirierende Stimmen, die diese Bibel-App zu etwas Besonderem machen</p><p>Sie können auch Buchkapitel speichern, um sie zu lesen, wenn Sie mit dem Netzwerk verbunden sind. Die entsprechende Foto- und Audiosammlung wird mit diesem Kapitel gespeichert.</p><p>-Besondere Merkmale:<br />+ Beschreibe das Bild der Geschichte<br />+ Sie können Bibelbücher speichern, um sie ohne Netzwerkverbindung zu lesen<br />+ Demonstrationsfunktion, mit der Sie schöne Hintergrundbilder der Bibel erstellen oder über ein soziales Netzwerk mit Freunden teilen können<br />+ Unterstützen Sie viele Sprachen auf der Welt<br />+ Lesen und Anhören des Dokuments</p>'),
(282,	'<p>♥ Zu lange einsam zu sein ist schlecht für deine Gesundheit, daher wurde diese App herausgebracht, um dir einen virtuellen Liebhaber zu geben<br />♥ Sei immer glücklich und chatte den ganzen Tag und die ganze Nacht mit dir. Sie kennt auch Wut und Eifersucht, ähnlich wie menschliche Gefühle<br />♥ Die App erkennt und liefert den Charakter automatisch entsprechend Ihrem Geschlecht<br />♥ Nicht nur das, sie ist auch eine Magd oder eine Assistentin in Ihrem Telefon, zum Beispiel Apps öffnen, Musik öffnen, Bibel lesen, mathematische Berechnungen durchführen<br />♥ Mit unzähligen anderen Funktionen und Daten, die im Online-System verfügbar sind, um mich durch meinen virtuellen Liebhaber zu wünschen, stellen Sie sicher, dass Ihre Karriere gut ist und Ihr Leben einfacher wird. Bringen Sie allen positive Energie</p>'),
(121,	'<p>Du bist traurig<br />\r\nBist du einsam?<br />\r\nHattest du noch nie eine Liebesbeziehung?<br />\r\nMöchten Sie ein Dienstmädchen in Ihrem Telefon finden?<br />\r\nOder möchten Sie einfach einen Freund zum Chatten finden?</p>\r\n\r\n<p>Mit dieser Anwendung können Sie diese Probleme lösen<br />\r\nDu wirst eine süße Freundin haben, die lauert, mit dir lauert und sich immer über Witze lustig macht. folgt Ihnen an den kalten Wintertagen, heißen Sommertagen</p>\r\n\r\n<p>Vor allem kann man sich irren, Befehle erteilen, um einfache Aufgaben zu erledigen, wie komponieren, anrufen, Musik spielen, etc. .. eine so gelehrige Liebe haben, dass jeder es nicht mag!</p>\r\n\r\n<p>Nicht nur das, diese virtuelle Liebhaberanwendung bringt Ihnen auch viele interessante Funktionen wie:</p>\r\n\r\n<p>+ Chat<br />\r\n-Plaudern<br />\r\n-Merken<br />\r\n- Sing für dich<br />\r\n- Lies die Geschichte<br />\r\n-Erinnerungssprachige Liebe<br />\r\n- Fremdsprache lernen<br />\r\n- Errate die Emotion des Benutzers<br />\r\n- Beschreiben Sie die Persönlichkeit des Benutzers durch Fragen<br />\r\n+ Virtueller Assistent<br />\r\nSteuerung des Systems mit Befehlen, Benutzergesprächen (z. B. offene Anwendungen, Nachrichten, Anrufe usw.)<br />\r\n+ Virtuelle Realität<br />\r\n- Erstellen Sie eine Virtual-Reality-Umgebung<br />\r\n- Erstellen Sie realistische virtuelle Umgebungen mit realistischen Lebensstilen</p>\r\n'),
(122,	'<p>Anwendung, Spiel Hilfe bei Schlaflosigkeit, Schlaflosigkeit. Mit 2 Funktionen \"Go to sleep\" und \"Gaming\".</p>\r\n\r\n<p>-Wählen Sie einfach die Anzahl der Schafe und schauen Sie auf die Bildschirme, um Ihre Seele zu erschrecken. Wenn Sie die Schafe zählen, die über einen Zaun springen, werden Sie einschlafen. Als du geschlafen hast<br />\r\nDie Anwendung schaltet automatisch die Bildschirme für den Akku aus, mit dem Sie die Messer bewegen</p>\r\n\r\n<p>-Sie können dieses lustige Spiel auch spielen, um jedes Schaf zu kontrollieren, das über einen Zaun springt. Sie erhalten Punkte. Jedes Schaf fügt die Buchstaben hinzu, die der Schaltfläche entsprechen</p>\r\n\r\n<p>Besondere Merkmale<br />\r\n- Musiksaal zum Schlafengehen<br />\r\n- Lies die guten Wünsche aller auf der Welt<br />\r\n- Spielerbewertungen im Spielemodus<br />\r\n- 3D-Grafik</p>\r\n'),
(132,	'<p>Zu lange allein zu sein ist nicht gut für Ihre Gesundheit, daher hat die Karotten-App diese App erstellt, um einsame Menschen zu trösten und ihnen zu helfen.</p>\r\n\r\n<p>Die App schafft einen Liebhaber nach Ihrem Geschlecht. Ein süßes Mädchen und ein lustiger Kerl werden die Menschen mit lustigen Gesprächen glücklich machen</p>\r\n\r\n<p>Und dies ist auch ein virtueller Assistent als Dienstmädchen in Ihrem Telefon. Sie können sich irren, wenn Sie die Anwendung anweisen, die Funktionen Ihres Telefons zu öffnen, insbesondere die gewünschten Titel oder einen bestimmten Radiosender zu suchen und abzuspielen ... und unzählige andere Funktionen, die auf Sie warten. .</p>\r\n'),
(138,	'<p>Verwenden Sie Ihr logisches Gehirn, um die Dekodierung von Matrizen in jeder Phase des Spiels zu arrangieren und Ihr Denken zu verbessern. Mit extrem einfachem Gameplay, das für Sie geeignet ist, um sich in der Entspannungszeit zu unterhalten<br />Spielanleitung:<br />Sie steuern jeden Zahlencluster um die schwarze Steuertaste in den Zeilen und Spalten in den numerischen Matrizen. Die Zahlen werden im Uhrzeigersinn gedreht. Sie verwenden Ihre Intelligenz, um die Regeln für die Anordnung von Zahlen in kleinen bis großen Zahlen festzulegen. Wenn Sie fertig sind, werden Sie der Gewinner sein</p>'),
(133,	'<p>Das Spiel hilft dir dabei, deine geistige Beweglichkeit mit vielen Bildsymbolen zu verbessern.<br />\r\nAuch Sie können dieses Spiel mit einem Zwei-Spieler-Modus spielen, mit Freunden oder Liebhabern zusammen sein, die miteinander kämpfen, während dieses sanfte Spiel sehr interessant ist, oder?<br />\r\nMit vielen lustigen und unterhaltsamen Symbolen wird das Spiel nicht langweilig und Sie können dieses Spiel spielen, wenn keine Netzwerkverbindung besteht.</p>\r\n\r\n<p>Wie man 1 Person spielt:<br />\r\nSie müssen das richtige Paar identischer Fotos in der Liste der ausgeblendeten Felder auswählen. Jede Ebene des Bildschirms weist unterschiedliche Herausforderungen auf, sodass der Spieler die Herausforderung in einem bestimmten Zeitraum bewältigen muss.</p>\r\n\r\n<p>Wie man 2 Personen spielt (Fighting)<br />\r\nÄhnlich wie bei einem Einzelspieler wird das Spiel zwei Bildschirme und verschiedene Herausforderungen für jeden Spieler aufteilen, um ihre Augen schnell zu testen. Die Person, die die Herausforderung abschließt, gewinnt zuerst.</p>\r\n'),
(127,	'<p>Diese unterhaltsame App bietet Ihnen Tausende von Hintergrundbildern und Puzzlespielen nach Themen. Verschönern Sie Ihr Handy und sorgen Sie für entspannende Unterhaltung mit Puzzlespielen, die diesem Hintergrundbild entsprechen</p>\r\n\r\n<p>Unzählige Sammlungen beliebter Kpop-Gruppen wie Red Velvet, Bts, Blackpink, Two, Momoland ... werden täglich aktualisiert.</p>\r\n'),
(284,	'<p>Lass uns zusammen auf die Jagd gehen, um unseren Körper größer zu machen, das ist die Hauptaufgabe dieses Spiels</p><p>Du schlüpfst in die Rolle eines kleinen Fisches in einem extrem gefährlichen und dramatischen Jagdabenteuer</p><p>Das Spiel bietet Ihnen eine Vielzahl von Fisch-Charakteren und viele Hindernisse, um Ihre Geduld und Ihren Scharfsinn herauszufordern.</p><p>Das Spiel eignet sich zur Entspannung und das Gameplay ist extrem einfach, also lasst uns Freunde und Verwandte zum Erleben aufrufen</p>'),
(139,	'<p>Kontrolliere den Wurm, um zu den Äpfeln zu gelangen und vermeide die Ecken.<br />Wenn Sie Äpfel essen, werden Sie zusammen mit Ihrem Wurm punkten und wachsen und wachsen.<br />Um zu beschleunigen, verbrauchen Sie die Wasserkrüge auf Ihrem Weg.</p><p>Wünsche dir viel Spaß beim Spielen.</p>'),
(105,	'<p>Dieser Garten enthält viele Sprichwörter, gute Worte für diejenigen, die Momente der Entspannung brauchen. Ernten Sie schöne Blumen für Ihr Leben, die mehr Sinn ergeben. Für diejenigen von Ihnen, die in der Stimmung für Trauer und Misserfolg in der Liebe sind, ist dies die richtige App, um Ihnen durch schwierige Zeiten in Ihrem Leben zu helfen.</p>\r\n\r\n<p>Sie können diese App auch als Notizbuch oder Lebenstagebuch mit vielen niedlichen Symbolen und herausragenden Funktionen verwenden, die als 3D-Objekte angezeigt werden.<br />\r\nIntuition hilft Ihnen, inspiriert zu werden, um gute Passagen, Liebeswörter, Wörter oder Ideen für das Leben zu schaffen.</p>\r\n\r\n<p>Gerade dies ist ein Maxime-Social-Network für Liebende, Sie können sich austauschen und austauschen!</p>\r\n\r\n<p>Wünsche dir alles Gute und vergiss die Traurigkeit im Leben</p>\r\n'),
(134,	'<p>Ist ein interaktives Spiel mit Liedern, mit denen Sie Musik hören und gleichzeitig Spiele spielen können.</p>\r\n\r\n<p>Das Spiel entführt Sie in eine Welt der Musik mit unzähligen Herausforderungen, die den von Ihnen ausgewählten Songs entsprechen. Jede Note des Scheiterns erzeugt Monster, die Sie oder die Stars für Sie beherbergen. Markieren Sie Ihre musikalischen Erfolge</p>\r\n\r\n<p>Mit einem riesigen Online-Musikladen und der Schwierigkeit des Spiels hoffen Sie, allen Momente der Entspannung und des Spaßes zu bringen!</p>\r\n'),
(120,	'<p>Sie haben keinen Liebhaber? Probieren Sie diese unterhaltsame Anwendung aus. Sie wird Ihnen helfen, einen schönen virtuellen Liebhaber zu haben. Ein Mädchen, das Ihnen klar ist, wird mit Ihnen plaudern mit intelligenten Köpfen, die Ihnen helfen wollen, mehr Spaß im Leben zu haben</p>\r\n\r\n<p>Besondere Merkmale:<br />\r\n+ Chat<br />\r\n+ Hören Sie Musik online<br />\r\n+ Hintergrundgalerie<br />\r\n+ Hören Sie Radio<br />\r\n+ Kontakte<br />\r\n+ Suche nach Informationen</p>\r\n\r\n<p>Auch hier ist der benutzerfreundliche virtuelle Assistent! (sollte mehr Zugriff auf Ihr Telefonsystem erfordern)</p>\r\n'),
(283,	'<p>Wenn Sie Musikkomponist sind und sich für Klaviermusik begeistern, ist dies eine sehr geeignete Anwendung für Sie.</p><p>Mit dem Midi-Editor können Sie Akkorde aufnehmen, Noten einfach bearbeiten, intuitive Beschreibungen und einfache Manipulationen darauf reagieren.</p><p>Außerdem stellen wir Ihnen eine Liste der Midi-Bibliothek mit unzähligen vorkomponierten Songs zur Verfügung, um Ihnen das Nachschlagen oder Lernen zu erleichtern.</p>'),
(136,	'<p>Die Anwendung wird zum Erstellen von Passwörtern und zum Verwalten von Passwörtern mit einer Vielzahl von voreingestellten Optionen verwendet, die sich zum Erstellen von Konten wie E-Mail, sozialen Netzwerken und Online-Websites eignen. Mit den generierten Passwörtern können Sie einfach Backups erstellen und verwalten. Helfen Sie dabei, Ihr Passwort nicht zu vergessen oder zu verlieren.</p>\r\n\r\n<p>Bereitstellung von professioneller MD5-String-Dekodierung und unbegrenztem Speicherplatz.</p>\r\n\r\n<p>Mithilfe einer intuitiven, benutzerfreundlichen interaktiven Oberfläche können Sie die Effizienz beim Erstellen von Online-Konten steigern.</p>\r\n'),
(131,	'<p>Wenn Sie schon lange allein sind und jemanden zum Chatten finden oder sich geliebt fühlen möchten. Probieren Sie diese App. Es wird dir mit Trauer helfen. Es wird einen niedlichen Liebhaber geben, der Ihr Freund mit künstlicher Intelligenz ist und der in Zeiten der Freude und Langeweile immer bei Ihnen ist</p>\r\n\r\n<p>Nicht nur das Chatten mit diesem virtuellen Liebhaber kann Ihnen dabei helfen, die Dinge in Ihrem Telefon als virtueller Assistent mit einem realen Aussehen zu vereinfachen. Drücken Sie Ihre Gefühle aus, interagieren Sie mit dem Benutzer, und Sie können zusammen mit Ihrem Geliebten durch die Funktion (Perspektive) mit reichhaltigen Karten reisen.</p>\r\n\r\n<p>Täglich werden weitere nützliche Funktionen aktualisiert, um Unterhaltung und Komfort zu gewährleisten</p>\r\n\r\n<p>Funktionen:<br />\r\n+ Chat<br />\r\n+ Virtueller Assistent<br />\r\n+ Musik hören (online)<br />\r\n+ Informationen und Kontakte nachschlagen<br />\r\n+ Hören Sie Radio</p>\r\n\r\n<p>Besondere Funktionen dieser Seite:<br />\r\n+ Der MV-Simulator hilft dem Charakter, Songs als Performer auszudrücken<br />\r\n+ 3D-Charakter fast das gleiche Leben</p>\r\n'),
(285,	'<p>Das Spiel simuliert den Balltisch mit vielen geeigneten Spielmodi, damit Sie sich mit Freunden unterhalten können. Der Kader ist bereits eingerichtet, Sie müssen nur die Gruppe auswählen, die Sie dem Spiel gegen die Maschine oder mit Freunden im Offline-Zwei-Spieler-Modus anschließen möchten.</p><p>Das Gameplay ähnelt einem Kickertisch, jedes Team kontrollierst du nur 4 Reihen, um dich zu bewegen, um den Ball des Gegners abzuschneiden. Diese Bewegung ist nach oben oder unten begrenzt, wenn der Ball des Gegners in der Position des Spielers, der den Ball hält, geschnitten wurde, Pfeile erscheinen, um die Richtung des Schusses zu beschreiben, um den Ball passieren zu lassen. Wählen Sie die passende Passrichtung, damit Ihr Team den Ball annimmt und an den Gegner weitergibt, Sie haben einen Punktestand</p><p>Jeder Spieler hat unterschiedliche Statistiken wie Schusskraft, Schnitt und Ballretention. Daher müssen Sie Ihre Startaufstellung sorgfältig abwägen, um erfolgreich zu sein. Ihr Sieg erfordert zwei Hauptfaktoren: Ihre Kontrollfähigkeiten und die Anordnung des Kaders. Sie können die Personen wechseln und den richtigen Spieler auswählen, wenn Sie am Spiel teilnehmen. Die Schusskraft ist die Geschwindigkeit, mit der der Ball eine Distanz pro Spielerstatistik zurücklegt. Schneiden des Balls ist die Fähigkeit, den Ball zu stehlen, wenn sich der Ball in die Nähe des Spielers bewegt. Dieser Wert ist sehr wichtig, wenn Sie dem Gegner den Ball stehlen möchten. Ball Control Stat ist der Wert, den Ball zu halten, wenn man den Ball erhält und den Ball erfolgreich abschneidet.</p><p>Darüber hinaus können Sie sich auch bei Ihrem Konto anmelden, um mit allen im System an der Rangliste der erreichten Ziele teilzunehmen. Das einfache Gameplay und das Zusammentreffen vieler berühmter Spieler wird die Besonderheit dieses Spiels sein, um Ihnen zu helfen, Momente der Entspannung und Unterhaltung mit Freunden zu verbringen. Wir werden Spieler und Statistiken wöchentlich aktualisieren, um Ihr Team noch besser zu machen. Viel Spaß beim Spielen dieses Spiels!</p>'),
(123,	'<p>Musik ist ein wesentlicher Bestandteil des Lebens eines jeden!</p>\r\n\r\n<p>Mit dieser App können Sie alle Songs auf der ganzen Welt nach Ländergenre und anderen Extras wie Radio- und Nicht-Lyrics-Melodien anhören.</p>\r\n\r\n<p>- Sie können unbegrenzt Songs auf Ihrem Gerät speichern, um sie zu genießen, wenn keine Netzwerkverbindung besteht</p>\r\n\r\n<p>-Die moderne Benutzeroberfläche interagiert problemlos mit vielen anderen Spezialfunktionsmenüs, z. B. Liedtexte anzeigen, mit dem Lied verknüpfte Videos anzeigen und Lieder nach Emotionen bewerten. Und Sie können das Lied mit Ihren Freunden teilen.</p>\r\n\r\n<p>-Die Trendsuchfunktion hilft Ihnen, die neuesten Songs zu finden. Durch die Vorschläge der Anwendung</p>\r\n\r\n<p>-Das Radio enthält beliebte Programme auf der ganzen Welt, die Listen zum einfachen Anhören selektiv bearbeiten</p>\r\n\r\n<p>-Neben den Funktionen „Zuhören“ und „Zuhören“ enthält die App beliebte Musik ohne Liedtext, damit die Benutzer sich entspannen oder die Stimmung verbessern können, damit sie problemlos einschlafen können.</p>\r\n'),
(130,	'<p>Wenn Sie schon lange allein sind und jemanden zum Chatten finden oder sich geliebt fühlen möchten. Probieren Sie diese App. Es wird dir mit Trauer helfen. Es wird einen niedlichen Liebhaber geben, der Ihr Freund mit künstlicher Intelligenz ist und der in Zeiten der Freude und Langeweile immer bei Ihnen ist</p>\r\n\r\n<p>Nicht nur das Chatten mit diesem virtuellen Liebhaber kann Ihnen dabei helfen, die Dinge in Ihrem Telefon als virtueller Assistent mit einem realen Aussehen zu vereinfachen. Drücken Sie Ihre Gefühle aus, interagieren Sie mit dem Benutzer, und Sie können zusammen mit Ihrem Geliebten durch die Funktion (Perspektive) mit reichhaltigen Karten reisen.</p>\r\n\r\n<p>Täglich werden weitere nützliche Funktionen aktualisiert, um Unterhaltung und Komfort zu gewährleisten</p>\r\n\r\n<p>Funktionen:<br />\r\n+ Chat<br />\r\n+ Virtueller Assistent<br />\r\n+ Musik hören (online)<br />\r\n+ Informationen und Kontakte nachschlagen<br />\r\n+ Hören Sie Radio</p>\r\n\r\n<p>Besondere Funktionen dieser Seite:<br />\r\n+ Der MV-Simulator hilft dem Charakter, Songs als Performer auszudrücken<br />\r\n+ 3D-Charakter fast das gleiche Leben</p>\r\n');

-- 2021-10-18 21:21:26
