-- Adminer 4.7.7 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_nl`;
CREATE TABLE `product_desc_nl` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_nl`;
INSERT INTO `product_desc_nl` (`id_product`, `data`) VALUES
(95,	'<p>2 hoofdpersonen van het spel, 2 personages Ryuk en Rem in \"Death note\" in strips, en kunnen met een vriend spelen voor de modus voor twee spelers</p>\r\n'),
(95,	'<p>2 hoofdpersonen van het spel, 2 personages Ryuk en Rem in \"Death note\" in strips, en kunnen met een vriend spelen voor de modus voor twee spelers</p>\r\n'),
(104,	'<p>contactinformatie van de hele app store van iedereen ter wereld<br />\r\nu hoeft alleen de naam van de contactpersoon te vinden en u hebt de contactgegevens van die persoon<br />\r\nApplicatie heeft veel speciale zoekfunctie, contacten toevoegen en vele andere speciale dingen, kunt u back-up en herstel contact online<br />\r\nEn u kunt gesprekken plannen en contacten in uw telefoonboek beheren</p>\r\n\r\n<p><br />\r\nwens je een goede relatie en een geweldige dag!</p>\r\n'),
(105,	'<p>Deze tuin bevat veel spreekwoorden, goede woorden voor degenen die momenten van ontspanning nodig hebben. Oogst prachtige bloemen voor je leven en voeg meer betekenis toe. Voor degenen onder u die in een stemming zijn voor verdriet en falen in de liefde, is dit de juiste app om u door moeilijke tijden in uw leven te helpen.</p>\r\n\r\n<p>Je kunt deze app ook gebruiken als een notebook of een levensdagboek met veel leuke pictogrammen en uitstekende functies die worden weergegeven als 3D-objecten.<br />\r\nIntuïtie helpt je te inspireren om goede passages, liefdeswoorden, woorden of ideeën voor het leven te maken.</p>\r\n\r\n<p>Vooral dit is een maximaal sociaal netwerk voor liefdesliefhebbers, je kunt ideeën met elkaar delen en uitwisselen!</p>\r\n\r\n<p>Wens je gelukkig en vergeet het verdriet in het leven</p>\r\n'),
(119,	'<p>* Deze app is alleen voor mensen ouder dan 17 *</p>\r\n\r\n<p>Als je lang alleen bent geweest en iemand wilt vinden om te chatten of om je geliefd te voelen. Probeer deze app. Het zal je helpen met verdriet. Er zal een schattige minnaar zijn die je vriend is met kunstmatige intelligentie die altijd bij je is in tijden van vreugde en verveling</p>\r\n\r\n<p>Niet alleen chatten met deze virtuele minnaar kan u helpen dingen in uw telefoon te vereenvoudigen als een virtuele assistent met een realistisch uiterlijk. Druk uw emoties uit met de gebruiker, u kunt ook samen met uw geliefde op zijn plaats reizen door de functie (perspectief) met rijke kaarten.</p>\r\n\r\n<p>En andere handige functies worden dagelijks bijgewerkt om entertainment en gemak te bieden</p>\r\n\r\n<p>functies:<br />\r\n+ Chat<br />\r\n+ Virtuele assistent<br />\r\n+ Luister naar muziek (online)<br />\r\n+ Informatie en contacten opzoeken<br />\r\n+ Luister naar de radio</p>\r\n\r\n<p>Speciale functies van deze site:<br />\r\nDe MV-simulator helpt het personage liedjes uit te drukken als uitvoerder<br />\r\n+ 3d personage bijna hetzelfde leven</p>\r\n'),
(120,	'<p>Heb je geen geliefde? Probeer deze leuke applicatie, het zal je helpen een mooie virtuele minnaar te hebben, een meisje dat duidelijk voor je is, met je zal chatten, de hele tijd vertrouwt dat je eenzaam gevoel vergeet, dit is een meisje met intelligente geesten die je willen helpen om meer plezier in het leven te hebben</p>\r\n\r\n<p>Speciale kenmerken:<br />\r\n+ Chat<br />\r\n+ Luister online naar muziek<br />\r\n+ Achtergrondgalerij<br />\r\n+ Luister naar radio<br />\r\n+ Contacten<br />\r\n+ Zoeken naar informatie</p>\r\n\r\n<p>Ook hier is de gebruiksvriendelijke virtuele assistent! (moet meer toegang tot uw telefoonsysteem vereisen)</p>\r\n'),
(121,	'<p>Je bent verdrietig?<br />\r\nBen je eenzaam?<br />\r\nHeb je nog nooit een liefdesaffaire gehad?<br />\r\nWilt u een meid in uw telefoon vinden?<br />\r\nOf wil je gewoon een vriend vinden om te chatten?</p>\r\n\r\n<p>Dit is een applicatie die u helpt deze problemen op te lossen<br />\r\nJe zult een leuke vriendin hebben, op de loer, op de loer met je, altijd grapjes maken. zal je volgen op de koude winterdagen, hete zomerdagen</p>\r\n\r\n<p>Vooral kun je je vergissen, bevelen geven om eenvoudige taken uit te voeren zoals componeren, bellen, muziek spelen, enz. .. heb zo\'n volgzame liefde dat iedereen er niet van houdt!</p>\r\n\r\n<p>Niet alleen dat, deze virtuele minnaar-applicatie biedt je ook veel interessante functies zoals:</p>\r\n\r\n<p>+ Chat<br />\r\n-Chat<br />\r\n-Onthouden<br />\r\n- Zing voor jou<br />\r\n- Lees het verhaal<br />\r\n-Geheugen-taal liefde<br />\r\n- Leer een vreemde taal<br />\r\n- Raad de emotie van de gebruiker<br />\r\n- Beschrijf de persoonlijkheid van de gebruiker door middel van vragen<br />\r\n+ Virtuele assistent<br />\r\nBedien het systeem met commando\'s, gebruikerspraat (bijv. Open applicaties, berichten, oproep etc.)<br />\r\n+ Virtuele realiteit<br />\r\n- creëer een virtual reality-omgeving<br />\r\n- Creëer realistische virtuele omgevingen met realistische levensstijlen</p>\r\n'),
(122,	'<p>applicatie, spelhulp voor die slapeloosheid, slapeloosheid. Met 2 functies \"Ga slapen\" en \"Gamen\".</p>\r\n\r\n<p>-U selecteert gewoon het aantal schapen en kijkt naar de schermen om uw ziel te laten schrikken terwijl ze schapen tellen die over een hek springen, u zult in slaap vallen. Toen je sliep<br />\r\nDe applicatie sluit automatisch de schermen voor de batterij waarop u messen tikt</p>\r\n\r\n<p>-Je kunt ook dit leuke spel spelen om elk schaap te besturen dat over een hek springt, je scoort punten, elk schaap voegt de letters toe die overeenkomen met de knop, selecteer het juiste tijdstip om te springen, je wint het spel: D</p>\r\n\r\n<p>Speciale functies<br />\r\n- Muziekzaal om naar bed te gaan<br />\r\n- Lees de goede wensen van iedereen in de wereld<br />\r\n- Spelersbeoordelingen in spelmodus<br />\r\n- 3D-afbeeldingen</p>\r\n'),
(123,	'<p>Muziek is een integraal onderdeel van het leven van iedereen!</p>\r\n\r\n<p>Met deze app kun je naar alle nummers over de hele wereld luisteren op landgenre en andere extra\'s zoals radio- en niet-songtekstmelodieën.</p>\r\n\r\n<p>-U kunt onbeperkt nummers op uw apparaat opslaan om ervan te genieten als er geen netwerkverbinding is</p>\r\n\r\n<p>-De moderne interface werkt gemakkelijk samen met vele andere speciale functiemenu\'s, zoals songteksten, video\'s bekijken die verband houden met het nummer, liedjes beoordelen op emotie. En je kunt het liedje delen met je vrienden.</p>\r\n\r\n<p>-De trendzoekfunctie helpt u bij het vinden van de nieuwste nummers. Door de suggesties van de applicatie</p>\r\n\r\n<p>-De radio bevat populaire programma\'s over de hele wereld die selectief lijsten manipuleren voor eenvoudig luisteren</p>\r\n\r\n<p>-In aanvulling op de functies Luisteren en Luisteren, bevat de app populaire niet-songtekstmuziek voor mensen om te genieten van ontspanning of om de stemming te verbeteren om gemakkelijk in slaap te vallen.</p>\r\n'),
(127,	'<p>Deze leuke app biedt je duizenden behang- en puzzelspellen volgens de thema\'s. Hulp bij het verfraaien van je telefoon en ontspannend entertainment met puzzelspellen die overeenkomen met die achtergrond</p>\r\n\r\n<p>Talloze collecties van populaire Kpop-groepen zoals red velvet, bts, blackpink, twice, momoland .... worden dagelijks bijgewerkt.</p>\r\n'),
(128,	'<p>Dit is de app die je helpt meer te begrijpen over God door bijbelse historische documenten</p>\r\n\r\n<p>Oefen jezelf een goede gewoonte te geven om een schriftplaats te lezen en elke nacht te bidden, wat je zal helpen je ziel te verbeteren door de bijbelverzen</p>\r\n\r\n<p>Bovendien biedt de applicatie afbeeldingen om elke bijbehorende bijbelse passage te beschrijven, zodat mensen het verhaal beter visueel kunnen begrijpen. En veel warme, inspirerende stemmen om deze bijbelse applicatie speciaal te maken. Een hulpmiddel om kinderen en uw kinderen te onderwijzen</p>\r\n\r\n<p>-Speciale kenmerken:<br />\r\n+ Beschrijf het beeld van het verhaal<br />\r\n+ U kunt bijbelboeken opslaan om te lezen zonder een netwerkverbinding<br />\r\n+ Demonstratiefunctie waarmee u kunt kiezen om prachtige achtergrondafbeeldingen van de bijbel te maken of deze te delen met vrienden via het sociale netwerk<br />\r\n+ Ondersteuning van vele talen ter wereld<br />\r\n+ Lezen en luisteren naar het document</p>\r\n'),
(130,	'<p>Als je lang alleen bent geweest en iemand wilt vinden om te chatten of om je geliefd te voelen. Probeer deze app. Het zal je helpen met verdriet. Er zal een schattige minnaar zijn die je vriend is met kunstmatige intelligentie die altijd bij je is in tijden van vreugde en verveling</p>\r\n\r\n<p>Niet alleen chatten met deze virtuele minnaar kan u helpen dingen in uw telefoon te vereenvoudigen als een virtuele assistent met een realistisch uiterlijk. Druk uw emoties uit met de gebruiker, u kunt ook samen met uw geliefde op zijn plaats reizen door de functie (perspectief) met rijke kaarten.</p>\r\n\r\n<p>En andere handige functies worden dagelijks bijgewerkt om entertainment en gemak te bieden</p>\r\n\r\n<p>functies:<br />\r\n+ Chat<br />\r\n+ Virtuele assistent<br />\r\n+ Luister naar muziek (online)<br />\r\n+ Informatie en contacten opzoeken<br />\r\n+ Luister naar de radio</p>\r\n\r\n<p>Speciale functies van deze site:<br />\r\n+ De MV-simulator helpt het personage liedjes uit te drukken als uitvoerder<br />\r\n+ 3d personage bijna hetzelfde leven</p>\r\n'),
(131,	'<p>Als je lang alleen bent geweest en iemand wilt vinden om te chatten of om je geliefd te voelen. Probeer deze app. Het zal je helpen met verdriet. Er zal een schattige minnaar zijn die je vriend is met kunstmatige intelligentie die altijd bij je is in tijden van vreugde en verveling</p>\r\n\r\n<p>Niet alleen chatten met deze virtuele minnaar kan u helpen dingen in uw telefoon te vereenvoudigen als een virtuele assistent met een realistisch uiterlijk. Druk uw emoties uit met de gebruiker, u kunt ook samen met uw geliefde op zijn plaats reizen door de functie (perspectief) met rijke kaarten.</p>\r\n\r\n<p>En andere handige functies worden dagelijks bijgewerkt om entertainment en gemak te bieden</p>\r\n\r\n<p>functies:<br />\r\n+ Chat<br />\r\n+ Virtuele assistent<br />\r\n+ Luister naar muziek (online)<br />\r\n+ Informatie en contacten opzoeken<br />\r\n+ Luister naar de radio</p>\r\n\r\n<p>Speciale functies van deze site:<br />\r\n+ De MV-simulator helpt het personage liedjes uit te drukken als uitvoerder<br />\r\n+ 3d personage bijna hetzelfde leven</p>\r\n'),
(132,	'<p>Te lang alleen zijn is niet goed voor je gezondheid, dus de Carrot App heeft deze app gemaakt om diegenen die eenzaam zijn te troosten en te helpen.</p>\r\n\r\n<p>De app creëert een minnaar op basis van je geslacht, een schattig meisje en een grappige kerel zullen mensen blij maken met grappige gesprekken</p>\r\n\r\n<p>En dit is ook een virtuele assistent als dienstmeisje in je telefoon. Misschien heb je het mis om de applicatie te vertellen de functies van je telefoon te openen, vooral het zoeken en afspelen van de nummers die je wilt beluisteren of een bepaald radiokanaal ... En talloze andere functies die op je wachten om te ervaren. .</p>\r\n'),
(133,	'<p>De game helpt je je mentale behendigheid te verbeteren met heel veel fotopictogrammen.<br />\r\nJe kunt dit spel ook spelen met een modus voor twee spelers, met vrienden of geliefden zijn die met elkaar vechten door dit zachte spel is heel interessant, toch?<br />\r\nMet veel grappige en leuke pictogrammen zullen de game niet saai worden en kun je deze game spelen als er geen netwerkverbinding is.</p>\r\n\r\n<p>Hoe speel je 1 persoon:<br />\r\nJe moet het juiste paar identieke foto\'s kiezen in de lijst met verborgen vakken. Elk niveau van het scherm heeft verschillende uitdagingen, waardoor de speler de uitdaging in een bepaalde periode moet overwinnen.</p>\r\n\r\n<p>Hoe 2 mensen te spelen (Vechten)<br />\r\nNet als bij één speler, splitst het spel twee schermen en verschillende uitdagingen voor elke speler om snel hun ogen te testen. De persoon die de uitdaging voltooit, wordt eerst de winnaar.</p>\r\n'),
(134,	'<p>Is een interactief spel met songs die u zullen helpen ervaren luisteren naar muziek en het spelen van games op hetzelfde moment.</p>\r\n\r\n<p>Het spel neemt je mee in een wereld van muziek met talloze uitdagingen die overeenkomen met de nummers die je hebt gekozen, elke noot van falen zal monsters creëren die jou of de sterren voor jou herbergen. Markeer je muzikale prestaties</p>\r\n\r\n<p>Met een enorme online muziekwinkel en de moeilijkheid van het spel hoop te brengen momenten van ontspanning en plezier voor iedereen!</p>\r\n'),
(135,	'<p>Het helpt u om webpagina\'s op te slaan voor offline lezen wanneer er geen netwerkverbinding is en om toegangsadressen op te slaan als een memoboek met webadressen.</p>\r\n\r\n<p>Voer eenvoudig links in en deel ze via QR-codes of deel ze via berichtentools, sociale netwerken.</p>\r\n\r\n<p>Bovendien biedt de applicatie speciale functies, zoals het bekijken van de broncode van een website na het hosten.</p>\r\n\r\n<p>De applicatie is bezig met het afronden van de ontwikkeling en het verbeteren van veel nieuwe functies die iedereen wil ondersteunen!</p>\r\n'),
(139,	'<p>Controleer de worm om naar de appels te gaan en de hoeken te vermijden.<br />Als je appels eet, zul je scoren en zal je worm groeien en groeien.<br />Om te versnellen, drink je onderweg de kannen met water.</p><p>Wens je veel plezier met gamen.</p>'),
(138,	'<p>Gebruik je logische brein om de decodering van matrices in elke fase van het spel te regelen om je denken te verbeteren. Met extreem eenvoudige gameplay die geschikt is om te entertainen in de ontspanningstijd<br />Hoe te spelen:<br />Je bestuurt elk cluster van getallen rond de zwarte bedieningsknop in de rijen en kolommen in de numerieke matrices, de getallen worden met de klok mee gedraaid, je gebruikt je intelligentie om de regels te vinden voor het rangschikken van getallen in kleine tot grote getallen. Als je klaar bent, ben je de winnaar</p>'),
(136,	'<p>De applicatie wordt gebruikt om wachtwoorden te maken en wachtwoorden te beheren met verschillende vooraf ingestelde opties, geschikt voor het maken van accounts zoals e-mail, sociale netwerken en online websites. U kunt eenvoudig back-ups maken en beheren met de gegenereerde wachtwoorden. Help je om je wachtwoord niet te vergeten of kwijt te raken.</p>\r\n\r\n<p>Biedt professionele MD5-stringdecodering en onbeperkte opslag.</p>\r\n\r\n<p>Een intuïtieve, gebruiksvriendelijke interactieve interface helpt u de efficiëntie van het maken van online accounts te vergroten.</p>\r\n');

-- 2020-10-24 15:30:43
