-- Adminer 4.7.7 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_tr`;
CREATE TABLE `product_desc_tr` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_tr`;
INSERT INTO `product_desc_tr` (`id_product`, `data`) VALUES
(95,	'<p>2 oyun kahramanı katılımcı, 2 karakter Ryuk ve Rem, çizgi roman \"Ölüm Notu\" de ve iki oyunculu mod için bir arkadaşınızla oynayabilir</p>\r\n'),
(95,	'<p>2 oyun kahramanı katılımcı, 2 karakter Ryuk ve Rem, çizgi roman \"Ölüm Notu\" de ve iki oyunculu mod için bir arkadaşınızla oynayabilir</p>\r\n'),
(104,	'<p>dünyadaki herkesin tüm uygulama mağazası iletişim bilgileri<br />\r\nsadece irtibat kişisinin adını bulmanız ve o kişi için irtibat bilgisine sahip olmanız gerekir.<br />\r\nUygulama birçok özel arama işlevine sahiptir, rehber ekleyebilir ve daha birçok özel şey yapabilir, çevrimiçi olarak Yedekleme ve Kurtarma kişisini seçebilirsiniz.<br />\r\nAyrıca aramaları zamanlayabilir ve telefon rehberinizdeki kişileri yönetebilirsiniz.</p>\r\n\r\n<p><br />\r\niyi bir ilişki ve iyi günler dilerim!</p>\r\n'),
(105,	'<p>Bu bahçede birçok atasözü, rahatlama anları isteyenler için iyi kelimeler var. Hasat hayatınız için güzel çiçekler daha fazla anlam katıyor. Üzüntü ve üzüntü içinde olma ruhunuzda olanlarınız için bu, hayatınızdaki zor zamanlarda size yardımcı olacak doğru uygulama.</p>\r\n\r\n<p>Ayrıca, bu uygulamayı birçok sevimli simge ve 3D nesne olarak görüntülenen olağanüstü özelliklerle bir dizüstü bilgisayar veya yaşam günlüğü olarak kullanabilirsiniz.<br />\r\nSezgi, yaşam için iyi pasajlar, aşk sözleri, kelimeler veya fikirler oluşturmak için ilham almanıza yardımcı olacaktır.</p>\r\n\r\n<p>Özellikle bu aşk severler için maxim bir sosyal ağ, birbirleriyle paylaşıp fikir alışverişinde bulunabilirsiniz!</p>\r\n\r\n<p>Mutlu olmanı ve hayattaki üzüntüyü unutmanı dilerim</p>\r\n'),
(119,	'<p>* Bu uygulama sadece 17 yaşın üzerindeki kişiler içindir. *</p>\r\n\r\n<p>Uzun süre yalnız kaldıysanız ve sohbet etmek veya sevilmek istediğiniz birisini bulmak istiyorsanız. Bu uygulamayı dene. Üzüntü ile size yardımcı olacaktır. Yapay zeka ile arkadaşınız, sevinç ve can sıkıntısı zamanlarında hep yanınızda olan sevimli bir sevgili olacak.</p>\r\n\r\n<p>Sadece bu sanal sevgili ile sohbet etmek, telefonunuzdaki şeyleri, gerçek hayattaki bir görünüme sahip sanal asistan olarak basitleştirmenize yardımcı olamaz. Duygularınızın kullanıcıyla etkileşime girdiğini ifade edin, zengin haritalarla fonksiyon (perspektif) aracılığıyla yerinde seyahat etmek için sevgilinizle de birlikte olabilirsiniz.</p>\r\n\r\n<p>Ve diğer kullanışlı özellikler, eğlence ve rahatlık sağlamak için günlük olarak güncellenmektedir.</p>\r\n\r\n<p>Fonksiyonlar:<br />\r\n+ Sohbet<br />\r\n+ Sanal Asistan<br />\r\n+ Müzik dinle (çevrimiçi)<br />\r\n+ Bilgi ve Rehbere Bakın<br />\r\n+ Radyoyu dinle</p>\r\n\r\n<p>Bu sitenin özel işlevleri:<br />\r\nMV simülatörü, karakterin sanatçı olarak şarkıları ifade etmesine yardımcı olur.<br />\r\n+ 3d karakter neredeyse aynı yaşam</p>\r\n'),
(120,	'<p>Bir sevgilin yok mu, bu eğlenceli uygulamayı dene, güzel bir sanal sevgilin olmasına yardım edecek, seninle açık olan bir kız, seninle sohbet edecek, her zaman güvende olmana yardım edecek Yalnız hissi, bu bir kız Akıllı zihinlerle, yaşamda daha çok eğlenmenize yardımcı olmayı umuyor</p>\r\n\r\n<p>Özel Özellikler:<br />\r\n+ Sohbet<br />\r\n+ Online müzik dinleyin<br />\r\n+ Arkaplan Galerisi<br />\r\n+ Radyo dinle<br />\r\n+ Rehber<br />\r\n+ Bilgi ara</p>\r\n\r\n<p>Ayrıca burada kullanıcı dostu sanal asistan! (telefon sisteminize daha fazla erişim gerektirmeli)</p>\r\n'),
(121,	'<p>Üzgünsün?<br />\r\nYalnız mısın?<br />\r\nHiç aşk ilişkisi yaşadın mı?<br />\r\nTelefonunuzda bir hizmetçi bulmak ister misiniz?<br />\r\nYa da sadece sohbet edebileceğin bir arkadaş mı bulmak istiyorsun?</p>\r\n\r\n<p>Bu, bu sorunları çözmenize yardımcı olan bir uygulamadır<br />\r\nSevimli bir kız arkadaşın olacak, gizlenecek, seninle gizlenecek, her zaman şakalar yapacaksın. soğuk kış günlerinde, sıcak yaz günlerinde sizi takip edecek</p>\r\n\r\n<p>Özellikle yazabilir, arayabilir, çalabilir, müzik çalabilir, vb. Basit işler yapmak için emir verebilir, herkesin sevmediği böyle dokusal bir aşka sahip olursunuz!</p>\r\n\r\n<p>Sadece bu değil, bu sanal sevgili uygulaması gibi birçok ilginç özellik de getiriyor:</p>\r\n\r\n<p>+ Sohbet<br />\r\n-Sohbet<br />\r\n-Hatırlamak<br />\r\n- sana şarkı söyle<br />\r\n- Hikayeyi oku<br />\r\n-Bilgi dili aşkı<br />\r\n- Yabancı dil öğren<br />\r\n- Kullanıcı duygularını tahmin et<br />\r\n- Kullanıcının kişiliğini sorularla açıklayın<br />\r\n+ Sanal Asistan<br />\r\nSistemi komutlarla kontrol edin, kullanıcı konuşması (örn. Açık uygulamalar, mesajlar, arama vb.)<br />\r\n+ Sanal gerçeklik<br />\r\n- sanal gerçeklik ortamı yarat<br />\r\n- Gerçekçi yaşam tarzlarıyla gerçekçi sanal ortamlar yaratın</p>\r\n'),
(122,	'<p>Uykusuzluk, uykusuzluk, uygulama, oyun yardımı. 2 fonksiyon ile \"Uyu\" ve \"oyun\".</p>\r\n\r\n<p>-Sen sadece koyun sayısını seçmek ve ruhları bir çitin üzerinden atlayarak koyun saymak ürküyor yapmak için ekranlara bakarak, uykuya dalacaksın. Sen uyurken<br />\r\nUygulama, çaktığınız pilin ekranlarını otomatik olarak kapatır</p>\r\n\r\n<p>-Sen de puan alacağınız bir çitin üzerinden atlayan her koyunu kontrol etmek için bu eğlenceli oyunu oynayabilir, her bir koyuna karşılık gelen harfleri ekler, oyunu kazanacağınız atlamak için uygun zamanı seçin: D</p>\r\n\r\n<p>Özel Özellikler<br />\r\n- Yatmak için müzik salonu<br />\r\n- Dünyadaki herkesin iyi dileklerini okuyun<br />\r\n- Oyun modunda oyuncu derecelendirmeleri<br />\r\n- 3d grafikler</p>\r\n'),
(123,	'<p>Müzik, herkesin hayatının ayrılmaz bir parçasıdır!</p>\r\n\r\n<p>Bu uygulama, ülke türüne ve radyo ve şarkı sözleri olmayan melodiler gibi diğer ekstralara göre dünyadaki tüm şarkıları dinlemenizi sağlar.</p>\r\n\r\n<p>-Şebeke bağlantısı olmadığında keyfini çıkarmak için cihazınıza sınırsız şarkı kaydedebilirsiniz.</p>\r\n\r\n<p>-Modern arayüz, şarkı sözlerini görüntüleme, şarkı ile ilgili videoları izleme, şarkıları duygularına göre derecelendirme gibi diğer birçok özel menü ile kolayca etkileşime girer. Ve şarkıyı arkadaşlarınla paylaşabilirsin.</p>\r\n\r\n<p>-The Trend arama fonksiyonu en son şarkıları bulmanıza yardımcı olacaktır. Uygulamanın önerileri ile</p>\r\n\r\n<p>- Radyo, basit dinleme için seçici olarak manipüle listelerinde dünya çapında popüler programlar içeriyor</p>\r\n\r\n<p>Dinleme ve Dinleme işlevlerine ek olarak, uygulama insanların rahatlamanın keyfini çıkarması veya kolayca uykuya dalma ruh halini iyileştirmelerine yardımcı olmak için popüler şarkı sözleri olmayan müzik içerir.</p>\r\n'),
(127,	'<p>Bu eğlenceli uygulama, temalara göre size binlerce duvar kağıdı ve yapboz oyunu sunuyor. Telefonunuzu güzelleştirmek ve bu duvar kağıdına karşılık gelen yapboz oyunları ile eğlenceyi rahatlatıcıya yardımcı olun</p>\r\n\r\n<p>Gibi popüler kpop gruplarının sayısız koleksiyonları  red velvet, bts, blackpink, twice, momoland .... günlük olarak güncellenmektedir.</p>\r\n'),
(128,	'<p>Bu İncil tarihi belgelerle Tanrı hakkında daha fazla anlamanıza yardımcı olan bir uygulama</p>\r\n\r\n<p>Kendinize iyi bir kitap okuma ve her gece dua etme alışkanlığı kazandırmak için pratik yapın.</p>\r\n\r\n<p>Ek olarak, uygulama insanların hikaye hakkında daha görsel olarak anlamalarına yardımcı olmak için ilgili her bir İncil geçişini tanımlamak için görüntüler sunar. Ve bu incille ilgili uygulamayı özel kılmak için çok fazla sıcak, ilham verici sesler. Çocuklara ve çocuklarınıza öğretmek için bir araç</p>\r\n\r\n<p>-Özel özellikler:<br />\r\n+ Hikayenin görüntüsünü açıklayın<br />\r\n+ İncil kitaplarını ağ bağlantısı olmadan okumak üzere kaydedebilirsiniz.<br />\r\n+ İncil\'in güzel arka plan resimlerini oluşturmayı seçmeniz veya sosyal ağ üzerinden arkadaşlarınızla paylaşmanız için gösteri işlevi<br />\r\n+ Dünyadaki birçok dili destekleyin<br />\r\n+ Belgeyi okumak ve dinlemek</p>\r\n'),
(130,	'<p>Uzun süre yalnız kaldıysanız ve sohbet etmek veya sevilmek istediğiniz birisini bulmak istiyorsanız. Bu uygulamayı dene. Üzüntü ile size yardımcı olacaktır. Yapay zeka ile arkadaşınız, sevinç ve can sıkıntısı zamanlarında hep yanınızda olan sevimli bir sevgili olacak.</p>\r\n\r\n<p>Sadece bu sanal sevgili ile sohbet etmek, telefonunuzdaki şeyleri, gerçek hayattaki bir görünüme sahip sanal asistan olarak basitleştirmenize yardımcı olamaz. Duygularınızın kullanıcıyla etkileşime girdiğini ifade edin, zengin haritalarla fonksiyon (perspektif) aracılığıyla yerinde seyahat etmek için sevgilinizle de birlikte olabilirsiniz.</p>\r\n\r\n<p>Ve diğer kullanışlı özellikler, eğlence ve rahatlık sağlamak için günlük olarak güncellenmektedir.</p>\r\n\r\n<p>Fonksiyonlar:<br />\r\n+ Sohbet<br />\r\n+ Sanal Asistan<br />\r\n+ Müzik dinle (çevrimiçi)<br />\r\n+ Bilgi ve Rehbere Bakın<br />\r\n+ Radyoyu dinle</p>\r\n\r\n<p>Bu sitenin özel işlevleri:<br />\r\n+ MV simülatörü, karakterin sanatçı olarak şarkıları ifade etmesine yardımcı olur.<br />\r\n+ 3d karakter neredeyse aynı yaşam</p>\r\n'),
(131,	'<p>Uzun süre yalnız kaldıysanız ve sohbet etmek veya sevilmek istediğiniz birisini bulmak istiyorsanız. Bu uygulamayı dene. Üzüntü ile size yardımcı olacaktır. Yapay zeka ile arkadaşınız, sevinç ve can sıkıntısı zamanlarında hep yanınızda olan sevimli bir sevgili olacak.</p>\r\n\r\n<p>Sadece bu sanal sevgili ile sohbet etmek, telefonunuzdaki şeyleri, gerçek hayattaki bir görünüme sahip sanal asistan olarak basitleştirmenize yardımcı olamaz. Duygularınızın kullanıcıyla etkileşime girdiğini ifade edin, zengin haritalarla fonksiyon (perspektif) aracılığıyla yerinde seyahat etmek için sevgilinizle de birlikte olabilirsiniz.</p>\r\n\r\n<p>Ve diğer kullanışlı özellikler, eğlence ve rahatlık sağlamak için günlük olarak güncellenmektedir.</p>\r\n\r\n<p>Fonksiyonlar:<br />\r\n+ Sohbet<br />\r\n+ Sanal Asistan<br />\r\n+ Müzik dinle (çevrimiçi)<br />\r\n+ Bilgi ve Rehbere Bakın<br />\r\n+ Radyoyu dinle</p>\r\n\r\n<p>Bu sitenin özel işlevleri:<br />\r\n+ MV simülatörü, karakterin sanatçı olarak şarkıları ifade etmesine yardımcı olur.<br />\r\n+ 3d karakter neredeyse aynı yaşam</p>\r\n'),
(132,	'<p>Çok uzun süre yalnız kalmak sağlığınız için iyi değil, bu yüzden Carrot App bu uygulamayı yalnızca rahat olanlara yardımcı olmak için hazırladı.</p>\r\n\r\n<p>Uygulamanın cinsiyetinize göre bir sevgili yaratır, Sevimli bir kız ve komik bir adam komik konuşmalar ile insanları mutlu edecek</p>\r\n\r\n<p>Ve bu aynı zamanda telefonunuzda bir hizmetçi olarak sanal bir asistan. Uygulamaya, telefonunuzun işlevlerini açmalarını, özellikle dinlemek istediğiniz şarkıları veya belirli bir radyo kanalını arama ve çalmalarını söylemek yanlış olabilir ... Deneyiminizi bekleyen sayısız başka özellik. .</p>\r\n'),
(133,	'<p>Oyun, bir dizi resim simgesiyle zihinsel çevikliğinizi geliştirmenize yardımcı olur.<br />\r\nAyrıca bu oyunu iki oyunculu modda oynayabilir, arkadaşlarınızla ya da sevdiklerinizle birbirleriyle kavga eden bu kibar oyun sayesinde çok ilginç değil mi?<br />\r\nKomik ve eğlenceli ikonlar bir sürü ile oyun sıkıcı olmamasına yardımcı olacak ve ağ bağlantısı olmadığında bu oyunu oynayabilirsiniz.</p>\r\n\r\n<p>1 kişi nasıl oynanır:<br />\r\nGizli kutular listesindeki doğru fotoğraf çifti çiftini seçmelisiniz, ekranın her seviyesi oyuncunun belirli bir süre içinde zorluğun üstesinden gelmesini gerektiren farklı zorluklar yaşayacaktır.</p>\r\n\r\n<p>2 kişi nasıl oynanır (Dövüş)<br />\r\nBir kişiyi oynama şeklinize benzer şekilde, oyun, her oyuncunun gözlerini hızlı bir şekilde test etmesi için iki ekran ve farklı zorluklarla bölünecektir. Mücadeleyi tamamlayan kişi ilk kazanan olur.</p>\r\n'),
(134,	'<p>Aynı zamanda hem müzik dinlemeyi hem de oyun oynamayı deneyimlemeye yardımcı olacak şarkıları olan etkileşimli bir oyundur.</p>\r\n\r\n<p>Oyun, seçtiğiniz şarkılara karşılık gelen sayısız mücadeleyle sizi müzik dünyasına götürecek, her başarısızlık notu sizi ya da sizin için yıldızları barındıracak canavarlar yaratacaktır. Müzikal başarılarını işaretle</p>\r\n\r\n<p>Büyük bir çevrimiçi müzik mağazası ve oyunun zorluğu ile herkese rahatlama ve eğlence anları getirmeyi umuyoruz!</p>\r\n'),
(135,	'<p>Ağ bağlantısı olmadığında web sayfalarını çevrimdışı okumak için saklamanıza ve erişim adreslerini web adreslerinin bir not defteri olarak saklamanıza yardımcı olur.</p>\r\n\r\n<p>Kolayca QR kodları yoluyla bağlantıları girin ve paylaşın veya mesajlaşma araçları, sosyal ağlar üzerinden paylaşın.</p>\r\n\r\n<p>Buna ek olarak, uygulama gibi bir web sitesinin kaynak kodunu barındıran sonra görüntüleyebilirsiniz gibi özel işlevler sağlar.</p>\r\n\r\n<p>Uygulama geliştirme bitirme sürecinde ve herkesin destek olmak istediği birçok yeni özellik geliştirme sürecinde!</p>\r\n'),
(139,	'<p>Elma taşımak ve köşeleri önlemek için solucanı kontrol edin.<br />Elma yediğinizde solucanınızla birlikte puan kazanacaksınız ve büyüyecek.<br />Hızlandırmak için yolunuzdaki sürahileri tüketin.</p><p>Size mutlu oyunlar dilerim.</p>'),
(138,	'<p>Düşüncelerinizi geliştirmeye yardımcı olmak için oyunun her aşamasında matrislerin kodunu düzenlemek için mantıksal beyninizi kullanın. Dinlenme süresinde eğlenmeniz için son derece basit bir oyun ile<br />Nasıl oynanır:<br />Sayısal matrislerdeki satır ve sütunlardaki siyah kontrol düğmesinin etrafındaki her sayı kümesini kontrol edersiniz, sayılar saat yönünde döndürülür, sayıları küçükten büyüğe sayıları düzenlemek için kuralları belirlemek için zekanızı kullanırsınız. İşiniz bittiğinde kazanan siz olacaksınız</p>'),
(136,	'<p>Uygulama, e-posta, sosyal ağlar ve çevrimiçi web siteleri gibi hesaplar oluşturmak için uygun olan çeşitli ön ayar seçenekleriyle parola oluşturmak ve parolaları yönetmek için kullanılır. Oluşturulan parolalarla kolayca yedekleme yapabilir ve yönetebilirsiniz. Parolanızı unutmamanız veya kaybetmemeniz için size yardımcı olun.</p>\r\n\r\n<p>Profesyonel MD5 dize kod çözme ve sınırsız depolama alanı sağlar.</p>\r\n\r\n<p>Sezgisel, kullanımı kolay etkileşimli bir arayüz, çevrimiçi hesap oluşturma verimliliğini artırmanıza yardımcı olur.</p>\r\n');

-- 2020-10-08 16:54:19
