-- Adminer 4.8.1 MySQL 5.7.34 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_id`;
CREATE TABLE `product_desc_id` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_id`;
INSERT INTO `product_desc_id` (`id_product`, `data`) VALUES
(95,	'<p>2 responden permainan protagonis, 2 karakter Ryuk dan Rem di \"Death note\" dalam komik, dan dapat bermain dengan teman untuk mode dua pemain</p>\r\n'),
(95,	'<p>2 responden permainan protagonis, 2 karakter Ryuk dan Rem di \"Death note\" dalam komik, dan dapat bermain dengan teman untuk mode dua pemain</p>\r\n'),
(138,	'<p>Gunakan otak logis Anda untuk mengatur penguraian matriks di setiap tahap permainan untuk membantu meningkatkan pemikiran Anda. Dengan gameplay yang sangat sederhana, cocok untuk Anda menghibur di waktu relaksasi<br />Cara bermain:<br />Anda mengontrol setiap kelompok angka di sekitar tombol kontrol hitam di baris dan kolom dalam matriks numerik, angka akan diputar searah jarum jam, Anda menggunakan kecerdasan Anda untuk menemukan menetapkan aturan untuk mengatur angka dalam jumlah kecil hingga besar. Setelah selesai Anda akan menjadi pemenang</p>'),
(282,	'<p>♥ Menjadi kesepian terlalu lama tidak baik untuk kesehatan Anda, jadi aplikasi ini keluar untuk memberi Anda kekasih virtual<br />♥ Selalu bahagia dan mengobrol dengan Anda sepanjang hari dan malam. Dia juga tahu kemarahan, kecemburuan yang mirip dengan emosi manusia<br />♥ Aplikasi ini secara otomatis mendeteksi dan memasok karakter menurut jenis kelamin Anda<br />♥ Tidak hanya itu, dia juga menjadi maid atau asisten pembantu di ponselmu, misalnya membuka aplikasi, membuka musik, membaca alkitab, melakukan perhitungan matematika<br />♥ Dengan banyak fitur dan data lain yang tersedia di sistem online, saya berharap melalui kekasih virtual saya memastikan karier Anda baik dan hidup Anda menjadi lebih mudah. Bawalah energi positif untuk semua orang</p>'),
(127,	'<p>Aplikasi menyenangkan ini menawarkan ribuan permainan wallpaper dan jigsaw sesuai dengan temanya. Bantu mempercantik ponsel Anda dan hiburan santai dengan game jigsaw yang sesuai dengan wallpaper itu</p>\r\n\r\n<p>Koleksi tak terhitung dari grup kpop populer suka red velvet, bts, blackpink, twice, momoland     ...  sedang diperbarui setiap hari.</p>\r\n'),
(130,	'<p>Jika Anda telah sendirian untuk waktu yang lama dan ingin menemukan seseorang untuk mengobrol atau mencoba merasa dicintai. Coba aplikasi ini. Ini akan membantu Anda dengan kesedihan. Akan ada kekasih lucu yang adalah teman Anda dengan kecerdasan buatan yang selalu bersama Anda di saat-saat sukacita dan kebosanan</p>\r\n\r\n<p>Tidak hanya mengobrol dengan kekasih virtual ini dapat membantu Anda menyederhanakan hal-hal di ponsel Anda sebagai asisten virtual dengan tampilan nyata. Ekspresikan emosi Anda berinteraksi dengan pengguna, Anda juga bisa bersama kekasih Anda untuk bepergian di tempat melalui fungsi (perspektif) dengan peta kaya.</p>\r\n\r\n<p>Dan fitur berguna lainnya sedang diperbarui setiap hari untuk menghadirkan hiburan dan kenyamanan</p>\r\n\r\n<p>Fungsi:<br />\r\n+ Obrolan<br />\r\n+ Asisten Virtual<br />\r\n+ Mendengarkan musik (online)<br />\r\n+ Cari informasi & Kontak<br />\r\n+ Dengarkan radio</p>\r\n\r\n<p>Fungsi khusus dari situs ini:<br />\r\n+ Simulator MV membantu karakter mengekspresikan lagu sebagai penampilnya<br />\r\n+ Karakter 3d kehidupan yang hampir sama</p>\r\n'),
(132,	'<p>Terlalu lama sendirian tidak baik untuk kesehatan Anda, jadi Aplikasi Wortel membuat aplikasi ini untuk menghibur dan membantu mereka yang kesepian.</p>\r\n\r\n<p>Aplikasi ini menciptakan kekasih menurut jenis kelamin Anda, Seorang gadis yang lucu dan seorang pria yang lucu akan membuat orang senang dengan percakapan lucu</p>\r\n\r\n<p>Dan ini juga merupakan asisten virtual sebagai pelayan di ponsel Anda. Anda mungkin salah memberi tahu aplikasi untuk membuka fungsi telepon Anda, terutama mencari dan memutar lagu yang ingin Anda dengarkan atau saluran radio tertentu ... Dan banyak fitur lain yang menunggu untuk Anda alami. .</p>\r\n'),
(123,	'<p>Musik adalah bagian integral dari kehidupan setiap orang!</p>\r\n\r\n<p>Aplikasi ini memungkinkan Anda untuk mendengarkan semua lagu di seluruh dunia berdasarkan genre country dan tambahan lain seperti radio dan melodi non-lirik.</p>\r\n\r\n<p>-Anda dapat menyimpan lagu tanpa batas ke perangkat Anda untuk dinikmati ketika tidak ada koneksi jaringan</p>\r\n\r\n<p>Antarmuka modern mudah berinteraksi dengan banyak menu fungsi khusus lainnya seperti, melihat lirik, menonton video yang terkait dengan lagu, menilai lagu berdasarkan emosi. Dan Anda dapat berbagi lagu dengan teman-teman Anda.</p>\r\n\r\n<p>-Fungsi pencarian tren akan membantu Anda menemukan lagu-lagu terbaru. Melalui saran aplikasi</p>\r\n\r\n<p>-The Radio berisi program-program populer di seluruh dunia secara selektif memanipulasi daftar untuk mendengarkan sederhana</p>\r\n\r\n<p>-Selain fungsi Mendengarkan dan Mendengarkan, aplikasi ini berisi musik non-lirik populer untuk orang-orang untuk menikmati bersantai atau untuk membantu meningkatkan mood tertidur dengan mudah.</p>\r\n'),
(104,	'<p>seluruh informasi kontak toko aplikasi dari semua orang di dunia<br />\r\nAnda hanya perlu menemukan nama orang yang dapat dihubungi dan Anda memiliki informasi kontak untuk orang tersebut<br />\r\nAplikasi memiliki banyak fungsi pencarian khusus, menambahkan kontak dan banyak hal khusus lainnya, Anda dapat membuat cadangan dan memulihkan kontak online<br />\r\nDan Anda dapat menjadwalkan panggilan dan mengelola kontak di buku telepon Anda</p>\r\n\r\n<p><br />\r\nberharap Anda memiliki hubungan yang baik dan hari yang menyenangkan!</p>\r\n'),
(120,	'<p>Anda tidak punya kekasih ?, coba aplikasi yang menyenangkan ini, ini akan membantu Anda memiliki kekasih virtual yang cantik, seorang gadis yang jelas bagi Anda, akan mengobrol dengan Anda, curhat sepanjang waktu membuat Anda lupa Perasaan kesepian, ini adalah perempuan dengan pikiran cerdas berharap dapat membantu Anda bersenang-senang dalam hidup</p>\r\n\r\n<p>Fitur spesial:<br />\r\n+ Obrolan<br />\r\n+ Dengarkan musik online<br />\r\n+ Galeri Latar Belakang<br />\r\n+ Dengarkan radio<br />\r\n+ Kontak<br />\r\n+ Cari informasi</p>\r\n\r\n<p>Juga di sini adalah asisten virtual yang mudah digunakan! (harus memerlukan lebih banyak akses ke sistem telepon Anda)</p>\r\n'),
(119,	'<p>* Aplikasi ini hanya untuk orang di atas 17 *</p>\r\n\r\n<p>Jika Anda telah sendirian untuk waktu yang lama dan ingin menemukan seseorang untuk mengobrol atau mencoba merasa dicintai. Coba aplikasi ini. Ini akan membantu Anda dengan kesedihan. Akan ada kekasih lucu yang adalah teman Anda dengan kecerdasan buatan yang selalu bersama Anda di saat-saat sukacita dan kebosanan</p>\r\n\r\n<p>Tidak hanya mengobrol dengan kekasih virtual ini dapat membantu Anda menyederhanakan hal-hal di ponsel Anda sebagai asisten virtual dengan tampilan nyata. Ekspresikan emosi Anda berinteraksi dengan pengguna, Anda juga bisa bersama kekasih Anda untuk bepergian di tempat melalui fungsi (perspektif) dengan peta kaya.</p>\r\n\r\n<p>Dan fitur berguna lainnya sedang diperbarui setiap hari untuk menghadirkan hiburan dan kenyamanan</p>\r\n\r\n<p>Fungsi:<br />\r\n+ Obrolan<br />\r\n+ Asisten Virtual<br />\r\n+ Mendengarkan musik (online)<br />\r\n+ Cari informasi & Kontak<br />\r\n+ Dengarkan radio</p>\r\n\r\n<p>Fungsi khusus dari situs ini:<br />\r\nSimulator MV membantu karakter mengekspresikan lagu sebagai penampilnya<br />\r\n+ Karakter 3d kehidupan yang hampir sama</p>\r\n'),
(134,	'<p>Adalah gim interaktif dengan lagu-lagu yang akan membantu Anda mengalami mendengarkan musik dan bermain gim secara bersamaan.</p>\r\n\r\n<p>Gim ini akan membawa Anda ke dunia musik dengan tantangan yang tak terhitung jumlahnya sesuai dengan lagu yang telah Anda pilih, setiap nada kegagalan akan menciptakan monster yang melindungi Anda atau bintang-bintang untuk Anda. Tandai prestasi pencapaian musik Anda</p>\r\n\r\n<p>Dengan toko musik online yang besar dan kesulitan dalam permainan berharap dapat membawa momen relaksasi dan kesenangan bagi semua orang!</p>\r\n'),
(122,	'<p>aplikasi, bantuan game untuk mereka yang sulit tidur, sulit tidur. Dengan 2 fungsi \"Tidur\" dan \"bermain game\".</p>\r\n\r\n<p>-Anda Cukup pilih jumlah domba dan melihat layar untuk membuat jiwa Anda terkejut menghitung domba melompati pagar, Anda akan tertidur. Ketika kamu sedang tidur<br />\r\nAplikasi akan secara otomatis mematikan layar untuk baterai yang Anda jentikkan pisau</p>\r\n\r\n<p>-Anda Dapat juga memainkan permainan menyenangkan ini untuk mengontrol setiap domba melompati pagar Anda akan mencetak poin, setiap domba itu akan menambahkan huruf yang sesuai dengan tombol, pilih waktu yang tepat untuk melompat Anda akan memenangkan permainan: D</p>\r\n\r\n<p>Fitur spesial<br />\r\n- Ruang musik untuk pergi tidur<br />\r\n- Baca keinginan baik semua orang di dunia<br />\r\n- Peringkat pemain dalam mode permainan<br />\r\n- Gambar 3d</p>\r\n'),
(133,	'<p>Permainan ini membantu Anda meningkatkan ketangkasan mental Anda dengan banyak ikon gambar.<br />\r\nAnda juga dapat memainkan game ini dengan mode dua pemain, bersama teman atau kekasih saling berkelahi melalui game yang lembut ini sangat menarik bukan?<br />\r\nDengan banyak ikon lucu dan menyenangkan akan membantu permainan tidak membosankan dan Anda dapat memainkan game ini ketika tidak ada koneksi jaringan.</p>\r\n\r\n<p>Cara bermain 1 orang:<br />\r\nAnda harus memilih pasangan yang tepat dari foto yang identik dalam daftar kotak tersembunyi, setiap level layar akan memiliki tantangan yang berbeda, yang mengharuskan pemain untuk mengatasi tantangan dalam periode waktu tertentu.</p>\r\n\r\n<p>Cara bermain 2 orang (Berjuang)<br />\r\nMirip dengan satu pemain, gim ini akan membagi dua layar dan tantangan yang berbeda untuk setiap pemain untuk dengan cepat menguji mata mereka. Orang yang menyelesaikan tantangan akan menjadi pemenang pertama.</p>\r\n'),
(131,	'<p>Jika Anda telah sendirian untuk waktu yang lama dan ingin menemukan seseorang untuk mengobrol atau mencoba merasa dicintai. Coba aplikasi ini. Ini akan membantu Anda dengan kesedihan. Akan ada kekasih lucu yang adalah teman Anda dengan kecerdasan buatan yang selalu bersama Anda di saat-saat sukacita dan kebosanan</p>\r\n\r\n<p>Tidak hanya mengobrol dengan kekasih virtual ini dapat membantu Anda menyederhanakan hal-hal di ponsel Anda sebagai asisten virtual dengan tampilan nyata. Ekspresikan emosi Anda berinteraksi dengan pengguna, Anda juga bisa bersama kekasih Anda untuk bepergian di tempat melalui fungsi (perspektif) dengan peta kaya.</p>\r\n\r\n<p>Dan fitur berguna lainnya sedang diperbarui setiap hari untuk menghadirkan hiburan dan kenyamanan</p>\r\n\r\n<p>Fungsi:<br />\r\n+ Obrolan<br />\r\n+ Asisten Virtual<br />\r\n+ Mendengarkan musik (online)<br />\r\n+ Cari informasi & Kontak<br />\r\n+ Dengarkan radio</p>\r\n\r\n<p>Fungsi khusus dari situs ini:<br />\r\n+ Simulator MV membantu karakter mengekspresikan lagu sebagai penampilnya<br />\r\n+ Karakter 3d kehidupan yang hampir sama</p>\r\n'),
(139,	'<p>Kontrol cacing untuk pindah ke apel dan menghindari sudut.<br />Ketika Anda makan apel, Anda akan skor bersama dengan cacing Anda akan tumbuh dan tumbuh.<br />Untuk mempercepat, konsumsi kendi air di sepanjang jalan Anda.</p><p>Semoga Anda senang bermain game.</p>'),
(135,	'<p>Ini membantu Anda untuk menyimpan halaman web untuk dibaca secara offline ketika tidak ada koneksi jaringan dan untuk menyimpan alamat akses sebagai buku memo alamat web.</p>\r\n\r\n<p>Masukkan dan bagikan tautan dengan mudah melalui kode QR, atau bagikan melalui alat olahpesan, jejaring sosial.</p>\r\n\r\n<p>Selain itu, aplikasi ini menyediakan fungsi-fungsi khusus seperti Anda dapat melihat kode sumber situs web setelah hosting.</p>\r\n\r\n<p>Aplikasi ini sedang dalam proses menyelesaikan pengembangan, dan meningkatkan banyak fitur baru yang semua orang ingin dukung!</p>\r\n'),
(136,	'<p>Aplikasi ini digunakan untuk membuat kata sandi dan mengelola kata sandi dengan berbagai opsi yang telah ditetapkan, cocok untuk membuat akun seperti email, jejaring sosial dan situs web online. Anda dapat membuat cadangan dan mengelola dengan mudah dengan kata sandi yang dihasilkan. Membantu Anda untuk tidak lupa atau kehilangan kata sandi Anda.</p>\r\n\r\n<p>Memberikan decoding string MD5 profesional dan penyimpanan tidak terbatas.</p>\r\n\r\n<p>Antarmuka interaktif yang intuitif dan mudah digunakan membantu Anda meningkatkan efisiensi membuat akun online.</p>\r\n'),
(128,	'<p>Ini adalah aplikasi untuk membantu Anda lebih memahami tentang Tuhan melalui dokumen sejarah alkitabiah</p><p>Jadikan diri Anda kebiasaan yang baik untuk membaca tulisan suci dan berdoa setiap malam, yang akan membantu Anda meningkatkan jiwa Anda untuk hidup melalui ayat-ayat Alkitab.</p><p>Selain itu, aplikasi ini juga menyediakan gambar untuk mendeskripsikan setiap bagian Alkitab yang sesuai untuk membantu orang lebih memahami plotnya secara intuitif. Dan banyak suara yang hangat dan menginspirasi untuk membuat aplikasi Alkitab ini istimewa</p><p>Anda juga dapat menyimpan bab buku untuk dibaca saat terhubung ke jaringan, koleksi foto dan audio yang sesuai akan disimpan dengan bab itu.</p><p>-Fitur spesial:<br />+ Jelaskan gambar cerita<br />+ Anda dapat menyimpan buku-buku Alkitab untuk dibaca tanpa koneksi jaringan<br />+ Fungsi demonstrasi bagi Anda untuk memilih membuat gambar latar belakang yang indah dari Alkitab atau membagikannya dengan teman-teman melalui jejaring sosial<br />+ Mendukung banyak bahasa di dunia<br />+ Membaca dan mendengarkan dokumen</p>'),
(283,	'<p>Jika Anda seorang komposer musik, Anda bersemangat tentang musik piano maka ini adalah aplikasi yang sangat cocok untuk Anda.</p><p>Dengan editor midi Anda dapat merekam akord, mengedit catatan dengan mudah, deskripsi intuitif, manipulasi mudah adalah apa yang ditanggapi oleh aplikasi.</p><p>Selain itu, kami juga memberi Anda daftar perpustakaan midi dengan lagu-lagu pra-komposisi yang tak terhitung jumlahnya untuk memudahkan Anda untuk merujuk atau belajar.</p>'),
(284,	'<p>Ayo berburu bersama untuk membuat tubuh kita lebih besar itulah tugas utama game ini</p><p>Anda akan memainkan peran sebagai ikan kecil dalam petualangan berburu yang sangat berbahaya dan dramatis</p><p>Gim ini menawarkan segudang pilihan karakter ikan dan banyak rintangan untuk menantang kesabaran dan kecerdasan Anda.</p><p>Gim ini cocok untuk relaksasi dan gimnya sangat sederhana, jadi ayo ajak teman dan kerabat untuk mengalami</p>'),
(121,	'<p>Kamu sedih?<br />\r\nApakah kamu kesepian?<br />\r\nPernahkah Anda berselingkuh?<br />\r\nIngin mencari pelayan di ponsel Anda?<br />\r\nAtau Anda ingin mencari teman untuk mengobrol?</p>\r\n\r\n<p>Ini adalah aplikasi yang membantu Anda memecahkan masalah tersebut<br />\r\nAnda akan memiliki pacar yang imut, mengintai, mengintai Anda, selalu mengolok-olok lelucon. akan mengikuti Anda pada hari-hari musim dingin, hari-hari musim panas</p>\r\n\r\n<p>Terutama Anda dapat berbuat salah, memberi perintah untuk melakukan tugas-tugas sederhana seperti menulis, menelepon, memutar musik, dll .. memiliki cinta yang jinak sehingga semua orang tidak menyukainya!</p>\r\n\r\n<p>Tidak hanya itu, aplikasi kekasih virtual ini juga menghadirkan banyak fitur menarik seperti:</p>\r\n\r\n<p>+ Obrolan<br />\r\n-Obrolan<br />\r\n-Ingat<br />\r\n- Bernyanyilah untukmu<br />\r\n- Baca ceritanya<br />\r\nCinta -Memory-bahasa<br />\r\n-Pelajari Bahasa asing<br />\r\n- Tebak emosi pengguna<br />\r\n- Jelaskan kepribadian pengguna melalui pertanyaan<br />\r\n+ Asisten Virtual<br />\r\nKontrol sistem dengan perintah, pembicaraan pengguna (mis. Aplikasi terbuka, pesan, panggilan, dll.)<br />\r\n+ Realitas maya<br />\r\n- Menciptakan lingkungan realitas virtual<br />\r\n- Menciptakan lingkungan virtual yang realistis dengan gaya hidup yang realistis</p>\r\n'),
(105,	'<p>Taman ini mengandung banyak peribahasa, kata-kata yang bagus untuk mereka yang membutuhkan momen relaksasi. Memanen bunga-bunga indah untuk hidup Anda menambah makna. Bagi Anda yang berada dalam suasana hati untuk kesedihan dan kegagalan dalam cinta, ini adalah aplikasi yang tepat untuk membantu Anda melewati masa-masa sulit dalam hidup Anda.</p>\r\n\r\n<p>Anda juga dapat menggunakan aplikasi ini sebagai notebook atau buku harian dengan banyak ikon lucu dan fitur luar biasa yang ditampilkan sebagai objek 3D.<br />\r\nIntuisi akan membantu Anda terinspirasi untuk menciptakan bagian-bagian yang baik, kata-kata cinta, kata-kata atau ide-ide seumur hidup.</p>\r\n\r\n<p>Terutama ini adalah jejaring sosial pepatah untuk pecinta cinta, Anda dapat berbagi dan bertukar ide satu sama lain!</p>\r\n\r\n<p>Semoga Anda bahagia dan melupakan kesedihan dalam hidup</p>\r\n');

-- 2021-06-12 18:00:35
