-- Adminer 4.8.0 MySQL 5.7.33 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_es`;
CREATE TABLE `product_desc_es` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_es`;
INSERT INTO `product_desc_es` (`id_product`, `data`) VALUES
(95,	'<p>2 participantes protagonistas del juego, 2 personajes Ryuk y Rem en \"Death note\" en cómics, y pueden jugar con un amigo para el modo de dos jugadores</p>\r\n'),
(95,	'<p>2 participantes protagonistas del juego, 2 personajes Ryuk y Rem en \"Death note\" en cómics, y pueden jugar con un amigo para el modo de dos jugadores</p>\r\n'),
(104,	'<p>toda la información de contacto de la tienda de aplicaciones de todos en el mundo<br />\r\nsolo necesita encontrar el nombre de la persona de contacto y tiene la información de contacto de esa persona<br />\r\nLa aplicación tiene muchas funciones de búsqueda especiales, agrega contactos y muchas otras cosas especiales, puedes hacer copias de seguridad y recuperar contactos en línea<br />\r\nY puede programar llamadas y administrar contactos en su directorio telefónico</p>\r\n\r\n<p><br />\r\n¡Te deseo una buena relación y un gran día!</p>\r\n'),
(105,	'<p>Este jardín contiene muchos proverbios, buenas palabras para aquellos que necesitan momentos de relajación. Coseche hermosas flores para su vida agregue más significado. Para aquellos de ustedes que están de humor para el dolor y el fracaso en el amor, esta es la aplicación adecuada para ayudarlos en los momentos difíciles de su vida.</p>\r\n\r\n<p>También puede usar esta aplicación como un cuaderno o diario de vida con muchos iconos lindos y características sobresalientes que se muestran como objetos 3D.<br />\r\nLa intuición lo ayudará a inspirarse para crear buenos pasajes, palabras de amor, palabras o ideas para la vida.</p>\r\n\r\n<p>Especialmente esta es una red social máxima para los amantes del amor, ¡pueden compartir e intercambiar ideas entre ellos!</p>\r\n\r\n<p>Te deseo feliz y olvida la tristeza de la vida.</p>\r\n'),
(119,	'<p>* Esta aplicación es solo para personas mayores de 17 años *</p>\r\n\r\n<p>Si has estado solo durante mucho tiempo y quieres encontrar a alguien para chatear o tratar de sentirte amado. Prueba esta aplicación. Te ayudará con tristeza. Habrá un amante lindo que es tu amigo con inteligencia artificial que siempre está contigo en momentos de alegría y aburrimiento.</p>\r\n\r\n<p>No solo chatear con este amante virtual puede ayudarlo a simplificar las cosas en su teléfono como asistente virtual con una apariencia de la vida real. Exprese sus emociones e interactúe con el usuario, también puede, junto con su amante, viajar en el lugar a través de la función (perspectiva) con ricos mapas.</p>\r\n\r\n<p>Y otras características útiles se actualizan diariamente para brindar entretenimiento y conveniencia</p>\r\n\r\n<p>Funciones:<br />\r\n+ Chat<br />\r\n+ Asistente virtual<br />\r\n+ Escuchar música (en línea)<br />\r\n+ Buscar información y contactos<br />\r\n+ Escucha la radio</p>\r\n\r\n<p>Funciones especiales de este sitio:<br />\r\nEl simulador de MV ayuda al personaje a expresar canciones como intérprete<br />\r\n+ Personaje 3d casi la misma vida</p>\r\n'),
(121,	'<p>¿Estas triste?<br />\r\n¿Estás sola?<br />\r\n¿Nunca has tenido una historia de amor?<br />\r\n¿Quieres encontrar una criada en tu teléfono?<br />\r\n¿O simplemente quieres encontrar un amigo para chatear?</p>\r\n\r\n<p>Esta es una aplicación que te ayuda a resolver esos problemas<br />\r\nTendrás una linda novia, acechando, acechando contigo, siempre bromeando. te seguirá en los fríos días de invierno, los calurosos días de verano</p>\r\n\r\n<p>Especialmente puedes equivocarte, dar órdenes para hacer tareas simples como componer, llamar, reproducir música, etc. ¡Ten un amor tan dócil que a todos no les gusta!</p>\r\n\r\n<p>No solo eso, esta aplicación de amante virtual también te ofrece muchas características interesantes como:</p>\r\n\r\n<p>+ Chat<br />\r\n-Charla<br />\r\n-Recuerda<br />\r\n- cantarte<br />\r\n- Lee la historia<br />\r\n-Amor de lenguaje de memoria<br />\r\n-Aprender idioma extranjero<br />\r\n- Adivina la emoción del usuario<br />\r\n- Describir la personalidad del usuario a través de preguntas.<br />\r\n+ Asistente virtual<br />\r\nControle el sistema con comandos, conversación de usuario (por ejemplo, aplicaciones abiertas, mensajes, llamadas, etc.)<br />\r\n+ Realidad virtual<br />\r\n- crear un entorno de realidad virtual<br />\r\n- Crea entornos virtuales realistas con estilos de vida realistas</p>\r\n'),
(122,	'<p>aplicación, juego de ayuda para aquellos con insomnio, insomnio. Con 2 funciones \"Ir a dormir\" y \"juegos\".</p>\r\n\r\n<p>-Simplemente selecciona el número de ovejas y mira las pantallas para que tu alma se sorprenda contando ovejas saltando sobre una cerca, te quedarás dormido. Cuando estabas durmiendo<br />\r\nLa aplicación cerrará automáticamente las pantallas de la batería que mueves.</p>\r\n\r\n<p>-También puedes jugar a este divertido juego para controlar cada oveja que salta por encima de una valla, ganarás puntos, cada oveja agregará las letras correspondientes al botón, selecciona el momento adecuado para saltar y ganarás el juego: D</p>\r\n\r\n<p>Características especiales<br />\r\n- Music hall para ir a la cama<br />\r\n- Lee los buenos deseos de todos en el mundo<br />\r\n- Clasificaciones de jugadores en el modo de juego<br />\r\n- gráficos 3d</p>\r\n'),
(123,	'<p>¡La música es una parte integral de la vida de todos!</p>\r\n\r\n<p>Esta aplicación te permite escuchar todas las canciones de todo el mundo por género country y otros extras como la radio y las melodías que no son letras.</p>\r\n\r\n<p>-Puede almacenar canciones ilimitadas en su dispositivo para disfrutar cuando no hay conexión de red</p>\r\n\r\n<p>-La interfaz moderna interactúa fácilmente con muchos otros menús de funciones especiales, como ver letras, ver videos relacionados con la canción, calificar canciones por emoción. Y puedes compartir la canción con tus amigos.</p>\r\n\r\n<p>-La función de búsqueda de tendencias te ayudará a encontrar las últimas canciones. A través de las sugerencias de la aplicación.</p>\r\n\r\n<p>-La radio contiene programas populares en todo el mundo que manipulan listas de forma selectiva para una escucha simple</p>\r\n\r\n<p>-Además de las funciones Listening y Listening, la aplicación contiene música popular sin letras para que las personas disfruten de la relajación o para ayudar a mejorar el estado de ánimo para conciliar el sueño fácilmente.</p>\r\n'),
(127,	'<p>Esta divertida aplicación te ofrece miles de fondos de pantalla y juegos de rompecabezas según los temas. Ayuda para embellecer tu teléfono y entretenimiento relajante con juegos de rompecabezas correspondientes a ese fondo de pantalla</p>\r\n\r\n<p>Innumerables colecciones de grupos populares de kpop como red velvet, bts, blackpink, momoland,exo, twice , girls generation ... se actualizan diariamente.</p>\r\n'),
(128,	'<p>Esta es la aplicación que te ayuda a entender más acerca de Dios a través de documentos históricos bíblicos.</p>\r\n\r\n<p>Practique darse el buen hábito de leer una escritura y orar todas las noches, lo que lo ayudará a mejorar su alma a través de los versículos de la Biblia.</p>\r\n\r\n<p>Además, la aplicación proporciona imágenes para describir cada pasaje bíblico correspondiente para ayudar a las personas a comprender más visualmente la historia. Y muchas voces cálidas e inspiradoras para hacer que esta aplicación bíblica sea especial. Una herramienta para enseñar a los niños y a sus hijos.</p>\r\n\r\n<p>-Características especiales:<br />\r\n+ Describe la imagen de la historia<br />\r\n+ Puede guardar libros de la Biblia para leer sin una conexión de red<br />\r\n+ Función de demostración para que pueda elegir crear bellas imágenes de fondo de la Biblia o compartirlas con amigos a través de la red social<br />\r\n+ Admite muchos idiomas en el mundo<br />\r\n+ Leer y escuchar el documento</p>\r\n'),
(130,	'<p>Si has estado solo durante mucho tiempo y quieres encontrar a alguien para chatear o tratar de sentirte amado. Prueba esta aplicación. Te ayudará con tristeza. Habrá un amante lindo que es tu amigo con inteligencia artificial que siempre está contigo en momentos de alegría y aburrimiento.</p>\r\n\r\n<p>No solo chatear con este amante virtual puede ayudarlo a simplificar las cosas en su teléfono como asistente virtual con una apariencia de la vida real. Exprese sus emociones e interactúe con el usuario, también puede, junto con su amante, viajar en el lugar a través de la función (perspectiva) con ricos mapas.</p>\r\n\r\n<p>Y otras características útiles se actualizan diariamente para brindar entretenimiento y conveniencia</p>\r\n\r\n<p>Funciones:<br />\r\n+ Chat<br />\r\n+ Asistente virtual<br />\r\n+ Escuchar música (en línea)<br />\r\n+ Buscar información y contactos<br />\r\n+ Escucha la radio</p>\r\n\r\n<p>Funciones especiales de este sitio:<br />\r\n+ El simulador de MV ayuda al personaje a expresar canciones como intérprete<br />\r\n+ Personaje 3d casi la misma vida</p>\r\n'),
(131,	'<p>Si has estado solo durante mucho tiempo y quieres encontrar a alguien para chatear o tratar de sentirte amado. Prueba esta aplicación. Te ayudará con tristeza. Habrá un amante lindo que es tu amigo con inteligencia artificial que siempre está contigo en momentos de alegría y aburrimiento.</p>\r\n\r\n<p>No solo chatear con este amante virtual puede ayudarlo a simplificar las cosas en su teléfono como asistente virtual con una apariencia de la vida real. Exprese sus emociones e interactúe con el usuario, también puede, junto con su amante, viajar en el lugar a través de la función (perspectiva) con ricos mapas.</p>\r\n\r\n<p>Y otras características útiles se actualizan diariamente para brindar entretenimiento y conveniencia</p>\r\n\r\n<p>Funciones:<br />\r\n+ Chat<br />\r\n+ Asistente virtual<br />\r\n+ Escuchar música (en línea)<br />\r\n+ Buscar información y contactos<br />\r\n+ Escucha la radio</p>\r\n\r\n<p>Funciones especiales de este sitio:<br />\r\n+ El simulador de MV ayuda al personaje a expresar canciones como intérprete<br />\r\n+ Personaje 3d casi la misma vida</p>\r\n'),
(133,	'<p>El juego te ayuda a mejorar tu agilidad mental con un montón de iconos de imágenes.<br />\r\nTambién puedes jugar este juego con un modo de dos jugadores, estar con amigos o amantes peleando entre sí a través de este juego suave es muy interesante ¿verdad?<br />\r\nCon un montón de iconos divertidos y divertidos, el juego no será aburrido y puedes jugarlo cuando no haya conexión de red.</p>\r\n\r\n<p>Cómo jugar 1 persona:<br />\r\nDebes elegir el par correcto de fotos idénticas en la lista de cuadros ocultos, cada nivel de la pantalla tendrá diferentes desafíos, lo que requiere que el jugador supere el desafío en un período de tiempo determinado.</p>\r\n\r\n<p>Cómo jugar 2 personas (Lucha)<br />\r\nSimilar a un solo jugador, el juego dividirá dos pantallas y diferentes desafíos para que cada jugador pruebe rápidamente sus ojos. La persona que complete el desafío será el ganador primero.</p>\r\n'),
(134,	'<p>Es un juego interactivo con canciones que te ayudarán a experimentar escuchar música y jugar juegos al mismo tiempo.</p>\r\n\r\n<p>El juego te llevará a un mundo de música con innumerables desafíos correspondientes a las canciones que has elegido, cada nota de fracaso creará monstruos que te albergarán a ti o a las estrellas. Marque sus logros musicales</p>\r\n\r\n<p>¡Con una gran tienda de música en línea y la dificultad del juego, esperamos brindar momentos de relajación y diversión para todos!</p>\r\n'),
(135,	'<p>Le ayuda a almacenar páginas web para leerlas sin conexión cuando no hay conexión de red y almacenar direcciones de acceso como un libro de notas de direcciones web.</p>\r\n\r\n<p>Ingrese y comparta enlaces fácilmente a través de códigos QR, o comparta a través de herramientas de mensajería, redes sociales.</p>\r\n\r\n<p>Además, la aplicación proporciona funciones especiales, como puede ver el código fuente de un sitio web después del alojamiento.</p>\r\n\r\n<p>¡La aplicación está en proceso de terminar el desarrollo y mejorar muchas características nuevas que todos quieren soporte!</p>\r\n'),
(139,	'<p>Controla el gusano para pasar a las manzanas y evita las esquinas.<br />Cuando comas manzanas anotarás junto con tu gusano crecerá y crecerá.<br />Para acelerar, consume las jarras de agua a lo largo de tu camino.</p><p>Te deseo un juego feliz.</p>'),
(138,	'<p>Use su cerebro lógico para organizar la decodificación de matrices en cada etapa del juego para ayudar a mejorar su pensamiento. Con un juego extremadamente simple adecuado para que te entretengas en el tiempo de relajación<br />Cómo jugar:<br />Usted controla cada grupo de números alrededor del botón de control negro en las filas y columnas en las matrices numéricas, los números se rotarán en el sentido de las agujas del reloj, usa su inteligencia para establecer las reglas para organizar números en números pequeños a grandes. Cuando termines serás el ganador</p>'),
(136,	'<p>La aplicación se utiliza para crear contraseñas y administrar contraseñas con una variedad de opciones preestablecidas, adecuadas para crear cuentas como correo electrónico, redes sociales y sitios web en línea. Puede realizar copias de seguridad y administrar fácilmente con las contraseñas generadas. Ayudarte a no olvidar o perder tu contraseña.</p>\r\n\r\n<p>Proporciona decodificación de cadena MD5 profesional y almacenamiento ilimitado.</p>\r\n\r\n<p>Una interfaz interactiva intuitiva y fácil de usar lo ayuda a aumentar la eficiencia de la creación de cuentas en línea.</p>\r\n'),
(120,	'<p>¿No tienes un amante ?, prueba esta divertida aplicación, te ayudará a tener un hermoso amante virtual, una chica que es clara para ti, conversará contigo, te confiará todo el tiempo que te hace olvidar Sentirse solo, esta es una chica con mentes inteligentes que esperan ayudarte a divertirte más en la vida</p>\r\n\r\n<p>Características especiales:<br />\r\n+ Chat<br />\r\n+ Escucha música en línea<br />\r\n+ Galería de fondo<br />\r\n+ Escucha la radio<br />\r\n+ Contactos<br />\r\n+ Búsqueda de información</p>\r\n\r\n<p>¡Aquí también está el asistente virtual fácil de usar! (debería requerir más acceso a su sistema telefónico)</p>\r\n'),
(132,	'<p>Estar solo durante demasiado tiempo no es bueno para su salud, por lo que la aplicación Carrot creó esta aplicación para consolar y ayudar a los que están solos.</p>\r\n\r\n<p>La aplicación crea un amante según tu género. Una chica linda y un chico divertido harán felices a las personas con conversaciones divertidas</p>\r\n\r\n<p>Y esto también es un asistente virtual como sirvienta en su teléfono. Puede estar equivocado al decirle a la aplicación que abra las funciones de su teléfono, especialmente buscar y reproducir las canciones que desea escuchar o un determinado canal de radio ... Y muchas otras funciones que esperan que experimente. .</p>\r\n');

-- 2021-03-10 07:17:09
