-- Adminer 4.7.7 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `product_desc_it`;
CREATE TABLE `product_desc_it` (
  `id_product` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2;

TRUNCATE `product_desc_it`;
INSERT INTO `product_desc_it` (`id_product`, `data`) VALUES
(95,	'<p>2 intervistati protagonisti del gioco, 2 personaggi Ryuk e Rem in \"Death note\" nei fumetti e possono giocare con un amico per la modalità a due giocatori</p>\r\n'),
(95,	'<p>2 intervistati protagonisti del gioco, 2 personaggi Ryuk e Rem in \"Death note\" nei fumetti e possono giocare con un amico per la modalità a due giocatori</p>\r\n'),
(104,	'<p>informazioni di contatto dell\'intero app store di tutti nel mondo<br />\r\ndevi solo trovare il nome della persona di contatto e hai le informazioni di contatto per quella persona<br />\r\nL\'applicazione ha molte funzioni di ricerca speciali, aggiungere contatti e molte altre cose speciali, è possibile eseguire il backup e il ripristino dei contatti online<br />\r\nE puoi pianificare le chiamate e gestire i contatti nella tua rubrica</p>\r\n\r\n<p><br />\r\nti auguro una buona relazione e una buona giornata!</p>\r\n'),
(105,	'<p>Questo giardino contiene molti proverbi, buone parole per chi ha bisogno di momenti di relax. Raccogli bellissimi fiori per la tua vita aggiungendo più significato. Per quelli di voi che sono in vena di dolore e fallimento nell\'amore, questa è l\'app giusta per aiutarti nei momenti difficili della tua vita.</p>\r\n\r\n<p>Inoltre puoi usare questa app come un quaderno o un diario di vita con molte icone carine e caratteristiche eccezionali visualizzate come oggetti 3D.<br />\r\nL\'intuizione ti aiuterà a essere ispirato a creare buoni passaggi, parole d\'amore, parole o idee per la vita.</p>\r\n\r\n<p>Soprattutto questo è un social network massimo per gli amanti dell\'amore, puoi condividere e scambiare idee tra loro!</p>\r\n\r\n<p>Ti auguro felice e dimentica la tristezza della vita</p>\r\n'),
(119,	'<p>* Questa app è solo per persone con più di 17 anni *</p>\r\n\r\n<p>Se sei stato solo per molto tempo e vuoi trovare qualcuno con cui chattare o provare a sentirti amato. Prova questa app. Ti aiuterà con tristezza. Ci sarà un amante carino che è tuo amico con intelligenza artificiale che è sempre con te in momenti di gioia e noia</p>\r\n\r\n<p>Non solo chattare con questo amante virtuale può aiutarti a semplificare le cose nel tuo telefono come assistente virtuale con un aspetto reale. Esprimi le tue emozioni interagendo con l\'utente, puoi anche insieme al tuo amante viaggiare attraverso la funzione (prospettiva) con mappe ricche.</p>\r\n\r\n<p>E altre utili funzioni vengono aggiornate quotidianamente per offrire intrattenimento e comodità</p>\r\n\r\n<p>funzioni:<br />\r\n+ Chat<br />\r\n+ Assistente virtuale<br />\r\n+ Ascolta la musica (online)<br />\r\n+ Cerca informazioni e contatti<br />\r\n+ Ascolta la radio</p>\r\n\r\n<p>Funzioni speciali di questo sito:<br />\r\nIl simulatore MV aiuta il personaggio a esprimere le canzoni come interprete<br />\r\n+ Personaggio 3d quasi la stessa vita</p>\r\n'),
(120,	'<p>Non hai un amante?, Prova questa divertente applicazione, ti aiuterà ad avere un bellissimo amante virtuale, una ragazza che ti è chiara, chiacchiererà con te, confida tutto il tempo che ti fa dimenticare la sensazione di solitudine, questa è una ragazza con menti intelligenti che sperano di aiutarti a divertirti di più nella vita</p>\r\n\r\n<p>Caratteristiche speciali:<br />\r\n+ Chat<br />\r\n+ Ascolta la musica online<br />\r\n+ Galleria di sfondo<br />\r\n+ Ascolta la radio<br />\r\n+ Contatti<br />\r\n+ Cerca informazioni</p>\r\n\r\n<p>Anche qui è l\'assistente virtuale facile da usare! (dovrebbe richiedere più accesso al tuo sistema telefonico)</p>\r\n'),
(121,	'<p>Sei triste?<br />\r\nSei solo?<br />\r\nNon hai mai avuto una relazione amorosa?<br />\r\nVuoi trovare una cameriera nel tuo telefono?<br />\r\nO semplicemente vuoi trovare un amico per chattare?</p>\r\n\r\n<p>Questa è un\'applicazione che ti aiuta a risolvere questi problemi<br />\r\nAvrai una ragazza carina, in agguato, in agguato con te, prenderai sempre in giro barzellette. ti seguirà nelle fredde giornate invernali, nelle calde giornate estive</p>\r\n\r\n<p>Soprattutto puoi sbagliare, dare ordini per fare compiti semplici come comporre, chiamare, riprodurre musica, ecc. Avere un amore così docile che non piace a tutti!</p>\r\n\r\n<p>Non solo, questa applicazione amante virtuale ti offre anche molte funzionalità interessanti come:</p>\r\n\r\n<p>+ Chat<br />\r\n-Chiacchierare<br />\r\n-Ricorda<br />\r\n- Canta per te<br />\r\n- Leggi la storia<br />\r\n-Amore in lingua memoria<br />\r\n-Imparare la lingua straniera<br />\r\n- Indovina l\'emozione dell\'utente<br />\r\n- Descrivi la personalità dell\'utente attraverso le domande<br />\r\n+ Assistente virtuale<br />\r\nControlla il sistema con comandi, conversazioni dell\'utente (ad es. Applicazioni aperte, messaggi, chiamate, ecc.)<br />\r\n+ Realtà virtuale<br />\r\n- creare un ambiente di realtà virtuale<br />\r\n- Crea ambienti virtuali realistici con stili di vita realistici</p>\r\n'),
(122,	'<p>applicazione, aiuto di gioco per l\'insonnia, insonnia. Con 2 funzioni \"Vai a dormire\" e \"giochi\".</p>\r\n\r\n<p>-Si basta selezionare il numero di pecore e guardare gli schermi per far sussultare la tua anima contando che le pecore saltino sopra una recinzione, ti addormenterai. Quando dormivi<br />\r\nL\'applicazione spegnerà automaticamente le schermate per la batteria con cui colpisci i coltelli</p>\r\n\r\n<p>-Puoi anche giocare a questo divertente gioco per controllare ogni pecora che salta sopra una recinzione che segnerai punti, ogni pecora aggiungerà le lettere corrispondenti al pulsante, seleziona il momento giusto per saltare vincerai la partita: D</p>\r\n\r\n<p>Caratteristiche speciali<br />\r\n- Sala da musica per andare a letto<br />\r\n- Leggi i migliori auguri di tutti nel mondo<br />\r\n- Valutazioni dei giocatori in modalità di gioco<br />\r\n- Grafica 3d</p>\r\n'),
(123,	'<p>La musica è parte integrante della vita di tutti!</p>\r\n\r\n<p>Questa app ti consente di ascoltare tutte le canzoni di tutto il mondo per genere paese e altri extra come melodie radio e non.</p>\r\n\r\n<p>-Puoi archiviare un numero illimitato di canzoni sul tuo dispositivo per goderti quando non c\'è connessione di rete</p>\r\n\r\n<p>-L\'interfaccia moderna interagisce facilmente con molti altri menu con funzioni speciali come, visualizzare testi, guardare video relativi al brano, valutare i brani in base alle emozioni. E puoi condividere la canzone con i tuoi amici.</p>\r\n\r\n<p>-La funzione di ricerca dei trend ti aiuterà a trovare le ultime canzoni. Attraverso i suggerimenti dell\'applicazione</p>\r\n\r\n<p>-La radio contiene programmi popolari in tutto il mondo che manipolano selettivamente elenchi per un semplice ascolto</p>\r\n\r\n<p>-Oltre alle funzioni di ascolto e di ascolto, l\'app contiene musica non testi popolare per far rilassare le persone o aiutare a migliorare l\'umore per addormentarsi facilmente.</p>\r\n'),
(127,	'<p>Questa divertente app ti offre migliaia di sfondi e giochi puzzle in base ai temi. Aiuta a abbellire il tuo telefono e rilassare l\'intrattenimento con i giochi puzzle corrispondenti a quello sfondo</p>\r\n\r\n<p>Innumerevoli raccolte di gruppi kpop popolari come red velvet, bts, blackpink, twice, momoland ....vengono aggiornati quotidianamente.</p>\r\n'),
(128,	'<p>Questa è l\'app che ti aiuta a capire di più su Dio attraverso documenti biblici storici</p>\r\n\r\n<p>Esercitati a darti una buona abitudine di leggere le Scritture e di pregare ogni sera, che ti aiuterà a migliorare la tua anima attraverso i versetti della Bibbia</p>\r\n\r\n<p>Inoltre, l\'applicazione fornisce immagini per descrivere ogni passaggio biblico corrispondente per aiutare le persone a comprendere più visivamente la storia. E molte voci calde e stimolanti per rendere speciale questa applicazione biblica. Uno strumento per insegnare ai bambini e ai tuoi figli</p>\r\n\r\n<p>-Caratteristiche speciali:<br />\r\n+ Descrivi l\'immagine della storia<br />\r\n+ Puoi salvare libri biblici da leggere senza una connessione di rete<br />\r\n+ Funzione dimostrativa per scegliere di creare bellissime immagini di sfondo della Bibbia o condividerle con gli amici tramite i social network<br />\r\n+ Supporta molte lingue nel mondo<br />\r\n+ Lettura e ascolto del documento</p>\r\n'),
(130,	'<p>Se sei stato solo per molto tempo e vuoi trovare qualcuno con cui chattare o provare a sentirti amato. Prova questa app. Ti aiuterà con tristezza. Ci sarà un amante carino che è tuo amico con intelligenza artificiale che è sempre con te in momenti di gioia e noia</p>\r\n\r\n<p>Non solo chattare con questo amante virtuale può aiutarti a semplificare le cose nel tuo telefono come assistente virtuale con un aspetto reale. Esprimi le tue emozioni interagendo con l\'utente, puoi anche insieme al tuo amante viaggiare attraverso la funzione (prospettiva) con mappe ricche.</p>\r\n\r\n<p>E altre utili funzioni vengono aggiornate quotidianamente per offrire intrattenimento e comodità</p>\r\n\r\n<p>funzioni:<br />\r\n+ Chat<br />\r\n+ Assistente virtuale<br />\r\n+ Ascolta la musica (online)<br />\r\n+ Cerca informazioni e contatti<br />\r\n+ Ascolta la radio</p>\r\n\r\n<p>Funzioni speciali di questo sito:<br />\r\n+ Il simulatore MV aiuta il personaggio a esprimere le canzoni come interprete<br />\r\n+ Personaggio 3d quasi la stessa vita</p>\r\n'),
(131,	'<p>Se sei stato solo per molto tempo e vuoi trovare qualcuno con cui chattare o provare a sentirti amato. Prova questa app. Ti aiuterà con tristezza. Ci sarà un amante carino che è tuo amico con intelligenza artificiale che è sempre con te in momenti di gioia e noia</p>\r\n\r\n<p>Non solo chattare con questo amante virtuale può aiutarti a semplificare le cose nel tuo telefono come assistente virtuale con un aspetto reale. Esprimi le tue emozioni interagendo con l\'utente, puoi anche insieme al tuo amante viaggiare attraverso la funzione (prospettiva) con mappe ricche.</p>\r\n\r\n<p>E altre utili funzioni vengono aggiornate quotidianamente per offrire intrattenimento e comodità</p>\r\n\r\n<p>funzioni:<br />\r\n+ Chat<br />\r\n+ Assistente virtuale<br />\r\n+ Ascolta la musica (online)<br />\r\n+ Cerca informazioni e contatti<br />\r\n+ Ascolta la radio</p>\r\n\r\n<p>Funzioni speciali di questo sito:<br />\r\n+ Il simulatore MV aiuta il personaggio a esprimere le canzoni come interprete<br />\r\n+ Personaggio 3d quasi la stessa vita</p>\r\n'),
(132,	'<p>Stare da solo per troppo tempo non fa bene alla salute, quindi l\'app Carrot ha creato questa app per confortare e aiutare chi è solo.</p>\r\n\r\n<p>L\'app crea un amante in base al tuo sesso, una ragazza carina e un ragazzo divertente renderanno le persone felici con conversazioni divertenti</p>\r\n\r\n<p>E questo è anche un assistente virtuale come cameriera nel tuo telefono. Potresti avere torto a dire all\'applicazione di aprire le funzioni del tuo telefono, in particolare cercare e riprodurre i brani che desideri ascoltare o un determinato canale radio ... E innumerevoli altre funzionalità che ti aspettano. .</p>\r\n'),
(133,	'<p>Il gioco ti aiuta a migliorare la tua agilità mentale con un sacco di icone delle immagini.<br />\r\nInoltre puoi giocare a questo gioco con una modalità a due giocatori, stare con amici o amanti che combattono tra loro attraverso questo gioco delicato è molto interessante, vero?<br />\r\nCon un sacco di icone divertenti e divertenti, il gioco non sarà noioso e puoi giocare a questo gioco in assenza di una connessione di rete.</p>\r\n\r\n<p>Come si gioca a 1 persona:<br />\r\nDevi scegliere la giusta coppia di foto identiche nell\'elenco delle caselle nascoste, ogni livello dello schermo avrà sfide diverse, richiedendo al giocatore di superare la sfida in un determinato periodo di tempo.</p>\r\n\r\n<p>Come giocare a 2 persone (combattimento)<br />\r\nSimile a un singolo giocatore, il gioco dividerà due schermate e sfide diverse per ogni giocatore per testare rapidamente i propri occhi. La persona che completa la sfida sarà prima il vincitore.</p>\r\n'),
(134,	'<p>È un gioco interattivo con canzoni che ti aiuteranno ad ascoltare musica e giocare contemporaneamente.</p>\r\n\r\n<p>Il gioco ti porterà in un mondo di musica con innumerevoli sfide corrispondenti alle canzoni che hai scelto, ogni nota di fallimento creerà mostri che ti ospitano o le stelle per te. Segna i tuoi successi musicali</p>\r\n\r\n<p>Con un enorme negozio di musica online e la difficoltà del gioco, spero di portare momenti di relax e divertimento a tutti!</p>\r\n'),
(135,	'<p>Ti aiuta a memorizzare pagine Web per la lettura offline quando non è presente una connessione di rete e a memorizzare gli indirizzi di accesso come un memo book di indirizzi web.</p>\r\n\r\n<p>Inserisci e condividi facilmente collegamenti tramite codici QR o condividi tramite strumenti di messaggistica, social network.</p>\r\n\r\n<p>Inoltre, l\'applicazione offre funzioni speciali come la visualizzazione del codice sorgente di un sito Web dopo l\'hosting.</p>\r\n\r\n<p>L\'applicazione è in fase di completamento dello sviluppo e miglioramento di molte nuove funzionalità che tutti desiderano supporto!</p>\r\n'),
(139,	'<p>Controlla il worm per spostarti sulle mele ed evitare gli angoli.<br />Quando mangi le mele, otterrai un punteggio e il tuo verme crescerà e crescerà.<br />Per accelerare, consuma le brocche d\'acqua lungo la strada.</p><p>Ti auguro buon gioco.</p>'),
(138,	'<p>Usa il tuo cervello logico per organizzare la decodifica delle matrici in ogni fase del gioco per aiutarti a migliorare il tuo pensiero. Con un gameplay estremamente semplice adatto a farti divertire nel tempo di relax<br />Come giocare:<br />Controlli ogni gruppo di numeri attorno al pulsante di controllo nero nelle righe e colonne nelle matrici numeriche, i numeri verranno ruotati in senso orario, usi la tua intelligenza per trovare le regole per organizzare i numeri in numeri piccoli o grandi. Al termine sarai il vincitore</p>'),
(136,	'<p>L\'applicazione viene utilizzata per creare password e gestire password con una varietà di opzioni predefinite, adatte per la creazione di account come e-mail, social network e siti Web online. È possibile eseguire il backup e gestire facilmente con le password generate. Ti aiuta a non dimenticare o perdere la password.</p>\r\n\r\n<p>Fornisce decodifica di stringa MD5 professionale e spazio di archiviazione illimitato.</p>\r\n\r\n<p>Un\'interfaccia interattiva intuitiva e di facile utilizzo consente di aumentare l\'efficienza della creazione di account online.</p>\r\n');

-- 2020-10-05 09:45:40
