-- Adminer 4.8.1 MySQL 5.7.37 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `country`;
CREATE TABLE `country` (
  `key` varchar(2) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

TRUNCATE `country`;
INSERT INTO `country` (`key`) VALUES
('vi'),
('en'),
('es'),
('pt'),
('fr'),
('hi'),
('zh'),
('ru'),
('de'),
('th'),
('ko'),
('ja'),
('ar'),
('tr'),
('fi'),
('it');

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `json`;
CREATE TABLE `json` (
  `id` varchar(100) NOT NULL,
  `name` varchar(50) NOT NULL,
  `data` text NOT NULL,
  `date` datetime NOT NULL,
  `user_lang` varchar(2) NOT NULL,
  `user_id` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE `json`;
INSERT INTO `json` (`id`, `name`, `data`, `date`, `user_lang`, `user_id`) VALUES
('61f3f90cd0d6161f3f90cd0d9d',	'thanh sss',	'{\n	\"Object 1\":{},\n	\"Object 2\":{},\n	\"Object 3\":{}\n}',	'2022-01-28 14:52:33',	'en',	'5ea856e920bd55ea856e920c10'),
('61f404d96ac1e61f404d96ac58',	'sdsd',	'{\n	\"Object 1\":{},\n	\"Object 2\":{}\n}',	'2022-01-28 14:59:37',	'vi',	'b3ee82bafceb3b5fc20824146b44ff2a'),
('61f404fbcb94f61f404fbcb98a',	'thanh',	'{\n	\"Object 1\":{},\n	\"Properties 2\":null,\n	\"Properties 3\":null,\n	\"Properties 4\":null,\n	\"Object 5\":{}\n}',	'2022-01-28 15:00:11',	'vi',	'b3ee82bafceb3b5fc20824146b44ff2a');

DROP TABLE IF EXISTS `lang_key`;
CREATE TABLE `lang_key` (
  `key` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE `lang_key`;
INSERT INTO `lang_key` (`key`) VALUES
('remove_ads'),
('remove_ads_tip'),
('setting'),
('help'),
('save'),
('app_sound'),
('app_sound_tip'),
('delete_all_data_tip'),
('in_app_restore'),
('in_app_restore_tip'),
('open'),
('new'),
('save_as'),
('editor'),
('coder'),
('compact'),
('new_file'),
('project_archives'),
('project_archives_tip'),
('name_of_project'),
('name_of_project_tip'),
('save_as_tip'),
('no_project'),
('json_root'),
('remove_ads_success'),
('project_name_error'),
('save_success'),
('p_update_success'),
('p_name_update_success'),
('p_upload_success'),
('share_project_tip'),
('import_file'),
('import'),
('import_tip'),
('import_url_tip'),
('import_url_error');

DROP TABLE IF EXISTS `lang_val`;
CREATE TABLE `lang_val` (
  `lang` varchar(2) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE `lang_val`;
INSERT INTO `lang_val` (`lang`, `data`) VALUES
('vi',	'{\"remove_ads\":\"Gỡ bỏ quảng cáo\",\"remove_ads_tip\":\"Mua hàng Không có quảng cáo trong ứng dụng\",\"setting\":\"Cài đặt\",\"help\":\"Hướng dẫn\",\"save\":\"Lưu lại\",\"app_sound\":\"Âm thanh\",\"app_sound_tip\":\"Bật hoặc tắt âm thanh trong ứng dụng\",\"delete_all_data_tip\":\"Xóa toàn bộ ứng dụng, đưa ứng dụng về trạng thái ban đầu (bao gồm cả mặt hàng đã mua)\",\"in_app_restore\":\"Khôi phục mua hàng\",\"in_app_restore_tip\":\"Khôi phục các chức năng và mặt hàng bạn đã mua trước đó\",\"open\":\"Mở\",\"new\":\"Mới\",\"save_as\":\"Lưu mới...\",\"editor\":\"Thiết kế\",\"coder\":\"Mã nguồn\",\"compact\":\"Rút gọn\",\"new_file\":\"Tập tin mới\",\"project_archives\":\"Lưu trữ Dự án\",\"project_archives_tip\":\"Lưu trữ chuỗi json của bạn để dễ dàng quản lý và truy xuất\",\"name_of_project\":\"Tên dự án\",\"name_of_project_tip\":\"Đặt tên cho dự án bạn muốn lưu\",\"save_as_tip\":\"Lưu trữ dự án này với tên khác\",\"no_project\":\"Bạn chưa có bất kỳ dự án nào được lưu trữ\",\"json_root\":\"Đối tượng gốc Json\",\"remove_ads_success\":\"Xóa quảng cáo thành công!\",\"project_name_error\":\"Tên dự án không được để trống!\",\"save_success\":\"Lưu dự án thành công !!!\",\"p_update_success\":\"Cập nhật dự án thành công!\",\"p_name_update_success\":\"Cập nhật tên dự án thành công!\",\"p_upload_success\":\"Lưu trữ dự án trực tuyến thành công!\",\"share_project_tip\":\"Chia sẻ dự án json này với những người khác\",\"import_file\":\"tệp nhập khẩu\",\"import\":\"Nhập khẩu\",\"import_tip\":\"Nhập dữ liệu json từ địa chỉ web\",\"import_url_tip\":\"Nhập url web json\",\"import_url_error\":\"Url đầu vào không được để trống!\"}'),
('en',	'{\"remove_ads\":\"Remove ads\",\"remove_ads_tip\":\"Purchase No In-App Ads\",\"setting\":\"Setting\",\"help\":\"Tutorial\",\"save\":\"Save\",\"app_sound\":\"Sound\",\"app_sound_tip\":\"Turn on or off the sound in the app\",\"delete_all_data_tip\":\"Delete the entire app, return the app to its original state (including purchased items)\",\"in_app_restore\":\"Restore purchase\",\"in_app_restore_tip\":\"Restore functions and items you previously purchased\",\"open\":\"Open\",\"new\":\"New\",\"save_as\":\"Save as...\",\"editor\":\"Editor\",\"coder\":\"Source code\",\"compact\":\"Compact\",\"new_file\":\"New file\",\"project_archives\":\"Project Archives\",\"project_archives_tip\":\"Store your json string for easy management and retrieval\",\"name_of_project\":\"Name of project\",\"name_of_project_tip\":\"Name the project you want to save\",\"save_as_tip\":\"Archive this project with another name\",\"no_project\":\"You don\'t have any archived projects yet\",\"json_root\":\"Json Root Object\",\"remove_ads_success\":\"Remove ads successfully!\",\"project_name_error\":\"Project name cannot be empty!\",\"save_success\":\"Save Project Success!!!\",\"p_update_success\":\"Project update successful!\",\"p_name_update_success\":\"Project name update successful!\",\"p_upload_success\":\"Successful online project hosting!\",\"share_project_tip\":\"Share this json project with others\",\"import_file\":\"Import file\",\"import\":\"Import\",\"import_tip\":\"Import json data from web address\",\"import_url_tip\":\"Enter json web url\",\"import_url_error\":\"Input url cannot be empty!\"}'),
('es',	'{\"remove_ads\":\"Quitar anuncios\",\"remove_ads_tip\":\"No compre anuncios en la aplicación\",\"setting\":\"Ajuste\",\"help\":\"Tutorial\",\"save\":\"Ahorrar\",\"app_sound\":\"Sonar\",\"app_sound_tip\":\"Activar o desactivar el sonido en la aplicación\",\"delete_all_data_tip\":\"Eliminar toda la aplicación, devolver la aplicación a su estado original (incluidos los artículos comprados)\",\"in_app_restore\":\"Restaurar compra\",\"in_app_restore_tip\":\"Restaura funciones y artículos que compraste anteriormente\",\"open\":\"Aberto\",\"new\":\"Nueva\",\"save_as\":\"Guardar como...\",\"editor\":\"Editor\",\"coder\":\"Código fuente\",\"compact\":\"Compacto\",\"new_file\":\"Archivo nuevo\",\"project_archives\":\"Archivos del proyecto\",\"project_archives_tip\":\"Almacene su cadena json para una fácil administración y recuperación\",\"name_of_project\":\"Nombre del proyecto\",\"name_of_project_tip\":\"Nombre el proyecto que desea guardar\",\"save_as_tip\":\"Archivar este proyecto con otro nombre\",\"no_project\":\"Aún no tienes ningún proyecto archivado\",\"json_root\":\"Objeto raíz Json\",\"remove_ads_success\":\"¡Elimine los anuncios con éxito!\",\"project_name_error\":\"¡El nombre del proyecto no puede estar vacío!\",\"save_success\":\"Guardar Proyecto Exitoso!!!\",\"p_update_success\":\"¡Actualización del proyecto exitosa!\",\"p_name_update_success\":\"¡Actualización exitosa del nombre del proyecto!\",\"p_upload_success\":\"¡Alojamiento exitoso de proyectos en línea!\",\"share_project_tip\":\"Comparte este proyecto json con otros\",\"import_file\":\"Importar archivo\",\"import\":\"importar\",\"import_tip\":\"Importar datos json desde la dirección web\",\"import_url_tip\":\"Ingrese la URL web json\",\"import_url_error\":\"¡La URL de entrada no puede estar vacía!\"}'),
('pt',	'{\"remove_ads\":\"Remover propagandas\",\"remove_ads_tip\":\"Não compre anúncios no aplicativo\",\"setting\":\"Contexto\",\"help\":\"Tutorial\",\"save\":\"Salve\",\"app_sound\":\"Som\",\"app_sound_tip\":\"Ativar ou desativar o som no aplicativo\",\"delete_all_data_tip\":\"Exclua todo o aplicativo, retorne o aplicativo ao seu estado original (incluindo itens comprados)\",\"in_app_restore\":\"Restaurar compra\",\"in_app_restore_tip\":\"Restaurar funções e itens que você comprou anteriormente\",\"open\":\"Aberto\",\"new\":\"Nova\",\"save_as\":\"Salvar como...\",\"editor\":\"Editor\",\"coder\":\"Código fonte\",\"compact\":\"Compactar\",\"new_file\":\"Novo arquivo\",\"project_archives\":\"Arquivos do projeto\",\"project_archives_tip\":\"Armazene sua string json para fácil gerenciamento e recuperação\",\"name_of_project\":\"Nome do projeto\",\"name_of_project_tip\":\"Dê um nome ao projeto que deseja salvar\",\"save_as_tip\":\"Arquivar este projeto com outro nome\",\"no_project\":\"Você ainda não tem projetos arquivados\",\"json_root\":\"Json do objeto raiz\",\"remove_ads_success\":\"Remova os anúncios com sucesso!\",\"project_name_error\":\"O nome do projeto não pode ficar vazio!\",\"save_success\":\"Salve o Sucesso do Projeto!!!\",\"p_update_success\":\"Atualização do projeto realizada com sucesso!\",\"p_name_update_success\":\"Atualização do nome do projeto bem-sucedida!\",\"p_upload_success\":\"Hospedagem de projetos online de sucesso!\",\"share_project_tip\":\"Compartilhe este projeto json com outras pessoas\",\"import_file\":\"Importar arquivo\",\"import\":\"importar\",\"import_tip\":\"Importar dados json do endereço da web\",\"import_url_tip\":\"Digite o URL da web json\",\"import_url_error\":\"O URL de entrada não pode estar vazio!\"}'),
('fr',	'{\"remove_ads\":\"Supprimez la pub\",\"remove_ads_tip\":\"N\'achetez pas de publicités dans l\'application\",\"setting\":\"Réglage\",\"help\":\"Didacticiel\",\"save\":\"Sauvegarder\",\"app_sound\":\"Sonner\",\"app_sound_tip\":\"Activer ou désactiver le son dans l\'application\",\"delete_all_data_tip\":\"Supprimer l\'intégralité de l\'application, remettre l\'application dans son état d\'origine (y compris les articles achetés)\",\"in_app_restore\":\"Restaurer l\'achat\",\"in_app_restore_tip\":\"Restaurer les fonctions et les éléments que vous avez achetés précédemment\",\"open\":\"Ouverte\",\"new\":\"Nouvelle\",\"save_as\":\"Enregistrer sous...\",\"editor\":\"Éditeur\",\"coder\":\"Code source\",\"compact\":\"Compacte\",\"new_file\":\"Nouveau fichier\",\"project_archives\":\"Archives du projet\",\"project_archives_tip\":\"Stockez votre chaîne json pour une gestion et une récupération faciles\",\"name_of_project\":\"Nom du projet\",\"name_of_project_tip\":\"Nommez le projet que vous souhaitez enregistrer\",\"save_as_tip\":\"Archiver ce projet sous un autre nom\",\"no_project\":\"Vous n\'avez pas encore de projets archivés\",\"json_root\":\"Objet racine Json\",\"remove_ads_success\":\"Supprimez les publicités avec succès !\",\"project_name_error\":\"Le nom du projet ne peut pas être vide !\",\"save_success\":\"Enregistrer le succès du projet !!!\",\"p_update_success\":\"Mise à jour du projet réussie !\",\"p_name_update_success\":\"Mise à jour du nom du projet réussie !\",\"p_upload_success\":\"Hébergement de projet en ligne réussi !\",\"share_project_tip\":\"Partager ce projet json avec d\'autres\",\"import_file\":\"Importer le fichier\",\"import\":\"importer\",\"import_tip\":\"Importer des données JSON à partir d\'une adresse Web\",\"import_url_tip\":\"Entrez l\'URL Web JSON\",\"import_url_error\":\"L\'URL d\'entrée ne peut pas être vide !\"}'),
('hi',	'{\"remove_ads\":\"विज्ञापन हटाएँ\",\"remove_ads_tip\":\"कोई इन-ऐप विज्ञापन नहीं खरीदें\",\"setting\":\"स्थापना\",\"help\":\"ट्यूटोरियल\",\"save\":\"सहेजें\",\"app_sound\":\"ध्वनि\",\"app_sound_tip\":\"ऐप में ध्वनि चालू या बंद करें\",\"delete_all_data_tip\":\"संपूर्ण ऐप हटाएं, ऐप को उसकी मूल स्थिति में लौटाएं (खरीदी गई वस्तुओं सहित)\",\"in_app_restore\":\"पुनःस्थापन क्रय\",\"in_app_restore_tip\":\"आपके द्वारा पहले खरीदे गए कार्यों और वस्तुओं को पुनर्स्थापित करें\",\"open\":\"खुला हुआ\",\"new\":\"नया\",\"save_as\":\"के रूप रक्षित करें...\",\"editor\":\"संपादक\",\"coder\":\"सोर्स कोड\",\"compact\":\"सघन\",\"new_file\":\"नई फ़ाइल\",\"project_archives\":\"परियोजना अभिलेखागार\",\"project_archives_tip\":\"आसान प्रबंधन और पुनर्प्राप्ति के लिए अपने जेसन स्ट्रिंग को स्टोर करें\",\"name_of_project\":\"परियोजना का नाम\",\"name_of_project_tip\":\"उस प्रोजेक्ट को नाम दें जिसे आप सहेजना चाहते हैं\",\"save_as_tip\":\"इस प्रोजेक्ट को किसी अन्य नाम से संग्रहित करें\",\"no_project\":\"आपके पास अभी तक कोई संग्रहीत प्रोजेक्ट नहीं है\",\"json_root\":\"मूल वस्तु Json\",\"remove_ads_success\":\"विज्ञापन सफलतापूर्वक निकालें!\",\"project_name_error\":\"प्रोजेक्ट का नाम खाली नहीं हो सकता!\",\"save_success\":\"परियोजना की सफलता बचाओ !!!\",\"p_update_success\":\"प्रोजेक्ट अपडेट सफल!\",\"p_name_update_success\":\"प्रोजेक्ट नाम अपडेट सफल!\",\"p_upload_success\":\"सफल ऑनलाइन प्रोजेक्ट होस्टिंग!\",\"share_project_tip\":\"इस जेसन प्रोजेक्ट को दूसरों के साथ साझा करें\",\"import_file\":\"फ़ाइल आयात करें\",\"import\":\"आयात\",\"import_tip\":\"वेब पते से json डेटा आयात करें\",\"import_url_tip\":\"जेसन वेब यूआरएल दर्ज करें\",\"import_url_error\":\"इनपुट यूआरएल खाली नहीं हो सकता!\"}'),
('zh',	'{\"remove_ads\":\"移除广告\",\"remove_ads_tip\":\"不购买应用内广告\",\"setting\":\"环境\",\"help\":\"教程\",\"save\":\"保存\",\"app_sound\":\"声音\",\"app_sound_tip\":\"在应用程序中打开或关闭声音\",\"delete_all_data_tip\":\"删除整个应用程序，将应用程序恢复到原始状态（包括购买的物品）\",\"in_app_restore\":\"恢复购买\",\"in_app_restore_tip\":\"恢复您之前购买的功能和项目\",\"open\":\"打开\",\"new\":\"新的\",\"save_as\":\"另存为...\",\"editor\":\"编辑\",\"coder\":\"源代码\",\"compact\":\"袖珍的\",\"new_file\":\"新文件\",\"project_archives\":\"项目档案\",\"project_archives_tip\":\"存储您的 json 字符串以便于管理和检索\",\"name_of_project\":\"项目名称\",\"name_of_project_tip\":\"命名您要保存的项目\",\"save_as_tip\":\"使用其他名称存档此项目\",\"no_project\":\"您还没有任何已归档的项目\",\"json_root\":\"根对象 Json\",\"remove_ads_success\":\"成功移除广告！\",\"project_name_error\":\"项目名称不能为空！\",\"save_success\":\"保存项目成功！！！\",\"p_update_success\":\"项目更新成功！\",\"p_name_update_success\":\"项目名称更新成功！\",\"p_upload_success\":\"成功的在线项目托管！\",\"share_project_tip\":\"与其他人分享这个 json 项目\",\"import_file\":\"导入文件\",\"import\":\"进口\",\"import_tip\":\"从网址导入json数据\",\"import_url_tip\":\"输入 json 网址\",\"import_url_error\":\"输入网址不能为空！\"}'),
('ru',	'{\"remove_ads\":\"Удалить рекламу\",\"remove_ads_tip\":\"Покупка без рекламы в приложении\",\"setting\":\"Параметр\",\"help\":\"Руководство\",\"save\":\"Сохранять\",\"app_sound\":\"Звук\",\"app_sound_tip\":\"Включить или выключить звук в приложении\",\"delete_all_data_tip\":\"Удалить все приложение, вернуть приложение в исходное состояние (включая купленные элементы)\",\"in_app_restore\":\"Восстановить покупку\",\"in_app_restore_tip\":\"Восстановление ранее приобретенных функций и предметов\",\"open\":\"Открытым\",\"new\":\"Новый\",\"save_as\":\"Сохранить как...\",\"editor\":\"редактор\",\"coder\":\"Исходный код\",\"compact\":\"Компактный\",\"new_file\":\"Новый файл\",\"project_archives\":\"Архивы проектов\",\"project_archives_tip\":\"Сохраните свою строку json для удобного управления и поиска\",\"name_of_project\":\"Название проекта\",\"name_of_project_tip\":\"Назовите проект, который вы хотите сохранить\",\"save_as_tip\":\"Заархивировать этот проект под другим именем\",\"no_project\":\"У вас пока нет заархивированных проектов\",\"json_root\":\"Корневой объект Json\",\"remove_ads_success\":\"Удалите рекламу успешно!\",\"project_name_error\":\"Название проекта не может быть пустым!\",\"save_success\":\"Сохранить успех проекта!!!\",\"p_update_success\":\"Обновление проекта успешно!\",\"p_name_update_success\":\"Название проекта успешно обновлено!\",\"p_upload_success\":\"Успешный хостинг интернет-проекта!\",\"share_project_tip\":\"Поделитесь этим проектом json с другими\",\"import_file\":\"Импортировать файл\",\"import\":\"Импортировать\",\"import_tip\":\"Импорт данных json с веб-адреса\",\"import_url_tip\":\"Введите веб-адрес json\",\"import_url_error\":\"Введите URL-адрес не может быть пустым!\"}'),
('de',	'{\"remove_ads\":\"Anzeigen entfernen\",\"remove_ads_tip\":\"Kaufen Sie keine In-App-Werbung\",\"setting\":\"Einstellung\",\"help\":\"Lernprogramm\",\"save\":\"Speichern\",\"app_sound\":\"Klang\",\"app_sound_tip\":\"Schalten Sie den Ton in der App ein oder aus\",\"delete_all_data_tip\":\"Löschen Sie die gesamte App, setzen Sie die App in ihren ursprünglichen Zustand zurück (einschließlich gekaufter Artikel).\",\"in_app_restore\":\"Kauf wiederherstellen\",\"in_app_restore_tip\":\"Stellen Sie zuvor gekaufte Funktionen und Artikel wieder her\",\"open\":\"Offen\",\"new\":\"Neu\",\"save_as\":\"Speichern als...\",\"editor\":\"Editor\",\"coder\":\"Quellcode\",\"compact\":\"Kompakt\",\"new_file\":\"Neue Datei\",\"project_archives\":\"Projektarchiv\",\"project_archives_tip\":\"Speichern Sie Ihre JSON-Zeichenfolge zur einfachen Verwaltung und zum einfachen Abrufen\",\"name_of_project\":\"Name des Projekts\",\"name_of_project_tip\":\"Benennen Sie das Projekt, das Sie speichern möchten\",\"save_as_tip\":\"Archivieren Sie dieses Projekt unter einem anderen Namen\",\"no_project\":\"Sie haben noch keine archivierten Projekte\",\"json_root\":\"Stammobjekt Json\",\"remove_ads_success\":\"Anzeigen erfolgreich entfernen!\",\"project_name_error\":\"Der Projektname darf nicht leer sein!\",\"save_success\":\"Projekterfolg speichern!!!\",\"p_update_success\":\"Projektaktualisierung erfolgreich!\",\"p_name_update_success\":\"Aktualisierung des Projektnamens erfolgreich!\",\"p_upload_success\":\"Erfolgreiches Online-Projekthosting!\",\"share_project_tip\":\"Teilen Sie dieses JSON-Projekt mit anderen\",\"import_file\":\"Datei importieren\",\"import\":\"importieren\",\"import_tip\":\"Importieren Sie json-Daten von der Webadresse\",\"import_url_tip\":\"Geben Sie die JSON-Web-URL ein\",\"import_url_error\":\"Eingabe-URL darf nicht leer sein!\"}'),
('th',	'{\"remove_ads\":\"ลบโฆษณา\",\"remove_ads_tip\":\"ซื้อไม่มีโฆษณาในแอป\",\"setting\":\"การตั้งค่า\",\"help\":\"กวดวิชา\",\"save\":\"บันทึก\",\"app_sound\":\"เสียง\",\"app_sound_tip\":\"เปิดหรือปิดเสียงในแอพ\",\"delete_all_data_tip\":\"ลบแอปทั้งหมด ให้แอปกลับสู่สถานะเดิม (รวมถึงรายการที่ซื้อ)\",\"in_app_restore\":\"เรียกคืนการซื้อ\",\"in_app_restore_tip\":\"คืนค่าฟังก์ชันและรายการที่คุณซื้อก่อนหน้านี้\",\"open\":\"เปิด\",\"new\":\"ใหม่\",\"save_as\":\"บันทึกเป็น...\",\"editor\":\"บรรณาธิการ\",\"coder\":\"รหัสแหล่งที่มา\",\"compact\":\"กะทัดรัด\",\"new_file\":\"ไฟล์ใหม่\",\"project_archives\":\"หอจดหมายเหตุโครงการ\",\"project_archives_tip\":\"จัดเก็บสตริง json ของคุณเพื่อให้ง่ายต่อการจัดการและดึงข้อมูล\",\"name_of_project\":\"ชื่อโครงการ\",\"name_of_project_tip\":\"ตั้งชื่อโครงการที่คุณต้องการบันทึก\",\"save_as_tip\":\"เก็บโครงการนี้ด้วยชื่ออื่น\",\"no_project\":\"คุณยังไม่มีโครงการที่เก็บถาวร\",\"json_root\":\"วัตถุราก Json\",\"remove_ads_success\":\"ลบโฆษณาสำเร็จ!\",\"project_name_error\":\"ชื่อโครงการไม่สามารถเว้นว่างได้!\",\"save_success\":\"บันทึกความสำเร็จของโครงการ!!!\",\"p_update_success\":\"อัปเดตโครงการสำเร็จแล้ว!\",\"p_name_update_success\":\"อัปเดตชื่อโครงการสำเร็จแล้ว!\",\"p_upload_success\":\"ประสบความสำเร็จในการโฮสต์โครงการออนไลน์!\",\"share_project_tip\":\"แชร์โครงการ json นี้กับผู้อื่น\",\"import_file\":\"นำเข้าไฟล์\",\"import\":\"นำเข้า\",\"import_tip\":\"นำเข้าข้อมูล json จากที่อยู่เว็บ\",\"import_url_tip\":\"ป้อน json web url\",\"import_url_error\":\"ต้องระบุ URL ที่ป้อน!\"}'),
('ko',	'{\"remove_ads\":\"광고를 제거하다\",\"remove_ads_tip\":\"인앱 광고 없음 구매\",\"setting\":\"환경\",\"help\":\"지도 시간\",\"save\":\"구하다\",\"app_sound\":\"소리\",\"app_sound_tip\":\"앱에서 소리 켜기 또는 끄기\",\"delete_all_data_tip\":\"전체 앱 삭제, 앱을 원래 상태로 되돌리기(구매한 항목 포함)\",\"in_app_restore\":\"구매 복원\",\"in_app_restore_tip\":\"이전에 구매한 기능 및 항목 복원\",\"open\":\"열려있는\",\"new\":\"새로운\",\"save_as\":\"다른 이름으로 저장...\",\"editor\":\"편집자\",\"coder\":\"소스 코드\",\"compact\":\"콤팩트\",\"new_file\":\"새로운 파일\",\"project_archives\":\"프로젝트 아카이브\",\"project_archives_tip\":\"쉬운 관리 및 검색을 위해 json 문자열을 저장하십시오.\",\"name_of_project\":\"프로젝트 이름\",\"name_of_project_tip\":\"저장하려는 프로젝트의 이름을 지정합니다.\",\"save_as_tip\":\"이 프로젝트를 다른 이름으로 보관\",\"no_project\":\"아직 보관된 프로젝트가 없습니다.\",\"json_root\":\"루트 개체 Json\",\"remove_ads_success\":\"광고를 성공적으로 제거하십시오!\",\"project_name_error\":\"프로젝트 이름은 비워둘 수 없습니다!\",\"save_success\":\"프로젝트 성공 저장!!!\",\"p_update_success\":\"프로젝트 업데이트 성공!\",\"p_name_update_success\":\"프로젝트 이름 업데이트 성공!\",\"p_upload_success\":\"성공적인 온라인 프로젝트 호스팅!\",\"share_project_tip\":\"이 json 프로젝트를 다른 사람들과 공유\",\"import_file\":\"파일 가져오기\",\"import\":\"수입\",\"import_tip\":\"웹 주소에서 json 데이터 가져오기\",\"import_url_tip\":\"json 웹 URL 입력\",\"import_url_error\":\"입력 URL은 비워둘 수 없습니다!\"}'),
('ja',	'{\"remove_ads\":\"広告を削除\",\"remove_ads_tip\":\"アプリ内広告を購入しない\",\"setting\":\"設定\",\"help\":\"チュートリアル\",\"save\":\"保存する\",\"app_sound\":\"音\",\"app_sound_tip\":\"アプリのサウンドをオンまたはオフにします\",\"delete_all_data_tip\":\"アプリ全体を削除し、アプリを元の状態に戻します（購入したアイテムを含む）\",\"in_app_restore\":\"購入商品を復元する\",\"in_app_restore_tip\":\"以前に購入した機能とアイテムを復元する\",\"open\":\"開ける\",\"new\":\"新しい\",\"save_as\":\"新規保管...\",\"editor\":\"編集者\",\"coder\":\"ソースコード\",\"compact\":\"コンパクト\",\"new_file\":\"新しいファイル\",\"project_archives\":\"プロジェクトアーカイブ\",\"project_archives_tip\":\"管理と取得を容易にするためにjson文字列を保存します\",\"name_of_project\":\"プロジェクト名\",\"name_of_project_tip\":\"保存するプロジェクトに名前を付けます\",\"save_as_tip\":\"このプロジェクトを別の名前でアーカイブする\",\"no_project\":\"アーカイブされたプロジェクトはまだありません\",\"json_root\":\"ルートオブジェクトJson\",\"remove_ads_success\":\"広告を正常に削除してください。\",\"project_name_error\":\"プロジェクト名を空にすることはできません！\",\"save_success\":\"プロジェクトの成功を保存します!!!\",\"p_update_success\":\"プロジェクトの更新に成功しました！\",\"p_name_update_success\":\"プロジェクト名の更新に成功しました！\",\"p_upload_success\":\"成功したオンラインプロジェクトホスティング！\",\"share_project_tip\":\"このjsonプロジェクトを他の人と共有する\",\"import_file\":\"インポートファイル\",\"import\":\"輸入\",\"import_tip\":\"Webアドレスからjsonデータをインポートする\",\"import_url_tip\":\"json weburlを入力します\",\"import_url_error\":\"入力URLを空にすることはできません！\"}'),
('ar',	'{\"remove_ads\":\"ازالة الاعلانات\",\"remove_ads_tip\":\"شراء أي إعلانات داخل التطبيق\",\"setting\":\"جلسة\",\"help\":\"درس تعليمي\",\"save\":\"يحفظ\",\"app_sound\":\"يبدو\",\"app_sound_tip\":\"قم بتشغيل أو إيقاف تشغيل الصوت في التطبيق\",\"delete_all_data_tip\":\"احذف التطبيق بالكامل ، وأعد التطبيق إلى حالته الأصلية (بما في ذلك العناصر المشتراة)\",\"in_app_restore\":\"استعادة شراء\",\"in_app_restore_tip\":\"استعادة الوظائف والعناصر التي اشتريتها مسبقًا\",\"open\":\"فتح\",\"new\":\"جديد\",\"save_as\":\"حفظ باسم...\",\"editor\":\"محرر\",\"coder\":\"مصدر الرمز\",\"compact\":\"المدمج\",\"new_file\":\"ملف جديد\",\"project_archives\":\"أرشيفات المشروع\",\"project_archives_tip\":\"قم بتخزين سلسلة json لإدارتها واسترجاعها بسهولة\",\"name_of_project\":\"اسم المشروع\",\"name_of_project_tip\":\"اسم المشروع الذي تريد حفظه\",\"save_as_tip\":\"أرشفة هذا المشروع باسم آخر\",\"no_project\":\"ليس لديك أي مشاريع مؤرشفة حتى الآن\",\"json_root\":\"الكائن الجذر Json\",\"remove_ads_success\":\"إزالة الإعلانات بنجاح!\",\"project_name_error\":\"لا يمكن أن يكون اسم المشروع فارغًا!\",\"save_success\":\"حفظ نجاح المشروع !!!\",\"p_update_success\":\"تم تحديث المشروع بنجاح!\",\"p_name_update_success\":\"تم تحديث اسم المشروع بنجاح!\",\"p_upload_success\":\"استضافة مشروع ناجح عبر الإنترنت!\",\"share_project_tip\":\"شارك مشروع json هذا مع الآخرين\",\"import_file\":\"استيراد ملف\",\"import\":\"يستورد\",\"import_tip\":\"استيراد بيانات json من عنوان الويب\",\"import_url_tip\":\"أدخل عنوان URL للويب json\",\"import_url_error\":\"لا يمكن أن يكون عنوان url الخاص بالإدخال فارغًا!\"}'),
('tr',	'{\"remove_ads\":\"Reklamları kaldırmak\",\"remove_ads_tip\":\"Uygulama İçi Reklam Satın Alma\",\"setting\":\"Ayar\",\"help\":\"öğretici\",\"save\":\"Kayıt etmek\",\"app_sound\":\"Ses\",\"app_sound_tip\":\"Uygulamada sesi açın veya kapatın\",\"delete_all_data_tip\":\"Tüm uygulamayı silin, uygulamayı orijinal durumuna getirin (satın alınan öğeler dahil)\",\"in_app_restore\":\"Satın almayı geri yükle\",\"in_app_restore_tip\":\"Daha önce satın aldığınız işlevleri ve öğeleri geri yükleyin\",\"open\":\"Açık\",\"new\":\"Yeni\",\"save_as\":\"Farklı kaydet...\",\"editor\":\"Editör\",\"coder\":\"Kaynak kodu\",\"compact\":\"Kompakt\",\"new_file\":\"Yeni dosya\",\"project_archives\":\"Proje Arşivleri\",\"project_archives_tip\":\"Kolay yönetim ve erişim için json dizinizi saklayın\",\"name_of_project\":\"projenin adı\",\"name_of_project_tip\":\"Kaydetmek istediğiniz projeyi adlandırın\",\"save_as_tip\":\"Bu projeyi başka bir adla arşivleyin\",\"no_project\":\"Henüz arşivlenmiş projeniz yok\",\"json_root\":\"Kök nesne Json\",\"remove_ads_success\":\"Reklamları başarıyla kaldırın!\",\"project_name_error\":\"Proje adı boş bırakılamaz!\",\"save_success\":\"Proje Başarısını Kaydet!!!\",\"p_update_success\":\"Proje güncellemesi başarılı!\",\"p_name_update_success\":\"Proje adı güncellemesi başarılı!\",\"p_upload_success\":\"Başarılı çevrimiçi proje barındırma!\",\"share_project_tip\":\"Bu json projesini başkalarıyla paylaşın\",\"import_file\":\"Önemli dosya\",\"import\":\"içe aktarmak\",\"import_tip\":\"json verilerini web adresinden içe aktarın\",\"import_url_tip\":\"json web url\'sini girin\",\"import_url_error\":\"Giriş url\'si boş olamaz!\"}'),
('fi',	'{\"remove_ads\":\"Poista mainokset\",\"remove_ads_tip\":\"Älä osta sovelluksen sisäisiä mainoksia\",\"setting\":\"Asetus\",\"help\":\"Opetusohjelma\",\"save\":\"Tallentaa\",\"app_sound\":\"Ääni\",\"app_sound_tip\":\"Ota ääni käyttöön tai poista se käytöstä sovelluksessa\",\"delete_all_data_tip\":\"Poista koko sovellus, palauta sovellus alkuperäiseen tilaan (mukaan lukien ostetut tuotteet)\",\"in_app_restore\":\"Palauta ostos\",\"in_app_restore_tip\":\"Palauta aiemmin ostamasi toiminnot ja kohteet\",\"open\":\"Avata\",\"new\":\"Uusi\",\"save_as\":\"Tallenna nimellä...\",\"editor\":\"Toimittaja\",\"coder\":\"Lähdekoodi\",\"compact\":\"Kompakti\",\"new_file\":\"Uusi tiedosto\",\"project_archives\":\"Projektiarkistot\",\"project_archives_tip\":\"Tallenna json-merkkijonosi helppoa hallintaa ja hakua varten\",\"name_of_project\":\"Projektin nimi\",\"name_of_project_tip\":\"Nimeä projekti, jonka haluat tallentaa\",\"save_as_tip\":\"Arkistoi tämä projekti toisella nimellä\",\"no_project\":\"Sinulla ei ole vielä arkistoituja projekteja\",\"json_root\":\"Json-juuriobjekti\",\"remove_ads_success\":\"Mainosten poistaminen onnistui!\",\"project_name_error\":\"Projektin nimi ei voi olla tyhjä!\",\"save_success\":\"Tallenna projektin menestys!!!\",\"p_update_success\":\"Projektipäivitys onnistui!\",\"p_name_update_success\":\"Projektin nimen päivitys onnistui!\",\"p_upload_success\":\"Onnistunut online-projektin isännöinti!\",\"share_project_tip\":\"Jaa tämä json-projekti muiden kanssa\",\"import_file\":\"Tuo tiedosto\",\"import\":\"tuonti\",\"import_tip\":\"Tuo json-tiedot verkko-osoitteesta\",\"import_url_tip\":\"Kirjoita json-verkko-URL-osoite\",\"import_url_error\":\"Syöte-url ei voi olla tyhjä!\"}'),
('it',	'{\"remove_ads\":\"Rimuovere gli annunci\",\"remove_ads_tip\":\"Non acquistare annunci in-app\",\"setting\":\"Collocamento\",\"help\":\"Esercitazione\",\"save\":\"Salva\",\"app_sound\":\"Suono\",\"app_sound_tip\":\"Attiva o disattiva l\'audio nell\'app\",\"delete_all_data_tip\":\"Elimina l\'intera app, riporta l\'app al suo stato originale (inclusi gli articoli acquistati)\",\"in_app_restore\":\"Ripristinare acquisto\",\"in_app_restore_tip\":\"Ripristina le funzioni e gli elementi acquistati in precedenza\",\"open\":\"Aprire\",\"new\":\"Nuova\",\"save_as\":\"Salva come...\",\"editor\":\"Editore\",\"coder\":\"Codice sorgente\",\"compact\":\"Compatto\",\"new_file\":\"Nuovo file\",\"project_archives\":\"Archivi di progetto\",\"project_archives_tip\":\"Archivia la tua stringa json per una facile gestione e recupero\",\"name_of_project\":\"Nome del progetto\",\"name_of_project_tip\":\"Assegna un nome al progetto che desideri salvare\",\"save_as_tip\":\"Archivia questo progetto con un altro nome\",\"no_project\":\"Non hai ancora nessun progetto archiviato\",\"json_root\":\"Oggetto radice Json\",\"remove_ads_success\":\"Rimuovere gli annunci con successo!\",\"project_name_error\":\"Il nome del progetto non può essere vuoto!\",\"save_success\":\"Salva il successo del progetto!!!\",\"p_update_success\":\"Aggiornamento del progetto riuscito!\",\"p_name_update_success\":\"Aggiornamento del nome del progetto riuscito!\",\"p_upload_success\":\"Hosting di progetti online di successo!\",\"share_project_tip\":\"Condividi questo progetto json con altri\",\"import_file\":\"Importare file\",\"import\":\"importare\",\"import_tip\":\"Importa i dati json dall\'indirizzo web\",\"import_url_tip\":\"Inserisci l\'URL web json\",\"import_url_error\":\"L\'URL di input non può essere vuoto!\"}'),
('id',	'{\"remove_ads\":\"Hilangkan iklan\",\"remove_ads_tip\":\"Beli Tanpa Iklan Dalam Aplikasi\",\"setting\":\"Pengaturan\",\"help\":\"tutorial\",\"save\":\"Menyimpan\",\"app_sound\":\"Suara\",\"app_sound_tip\":\"Mengaktifkan atau menonaktifkan suara di aplikasi\",\"delete_all_data_tip\":\"Hapus seluruh aplikasi, kembalikan aplikasi ke keadaan semula (termasuk item yang dibeli)\",\"in_app_restore\":\"Pulihkan pembelian\",\"in_app_restore_tip\":\"Pulihkan fungsi dan item yang Anda beli sebelumnya\",\"open\":\"Membuka\",\"new\":\"Baru\",\"save_as\":\"Simpan sebagai...\",\"editor\":\"Editor\",\"coder\":\"Kode sumber\",\"compact\":\"kompak\",\"new_file\":\"File baru\",\"project_archives\":\"Arsip Proyek\",\"project_archives_tip\":\"Simpan string json Anda untuk pengelolaan dan pengambilan yang mudah\",\"name_of_project\":\"Nama proyek\",\"name_of_project_tip\":\"Beri nama proyek yang ingin Anda simpan\",\"save_as_tip\":\"Arsipkan proyek ini dengan nama lain\",\"no_project\":\"Anda belum memiliki proyek yang diarsipkan\",\"json_root\":\"Akar objek Json\",\"remove_ads_success\":\"Hapus iklan dengan sukses!\",\"project_name_error\":\"Nama proyek tidak boleh kosong!\",\"save_success\":\"Simpan Sukses Proyek!!!\",\"p_update_success\":\"Pembaruan proyek berhasil!\",\"p_name_update_success\":\"Pembaruan nama proyek berhasil!\",\"p_upload_success\":\"Hosting proyek online yang sukses!\",\"share_project_tip\":\"Bagikan proyek json ini dengan orang lain\",\"import_file\":\"Impor file\",\"import\":\"impor\",\"import_tip\":\"Impor data json dari alamat web\",\"import_url_tip\":\"Masukkan url web json\",\"import_url_error\":\"Url masukan tidak boleh kosong!\"}'),
('da',	'{\"remove_ads\":\"Fjern annoncer\",\"remove_ads_tip\":\"Køb ingen annoncer i appen\",\"setting\":\"Indstilling\",\"help\":\"Tutorial\",\"save\":\"Gemme\",\"app_sound\":\"Lyd\",\"app_sound_tip\":\"Tænd eller sluk for lyden i appen\",\"delete_all_data_tip\":\"Slet hele appen, sæt appen tilbage til dens oprindelige tilstand (inklusive købte varer)\",\"in_app_restore\":\"Gendan køb\",\"in_app_restore_tip\":\"Gendan funktioner og varer, du tidligere har købt\",\"open\":\"Åben\",\"new\":\"Ny\",\"save_as\":\"Gem som...\",\"editor\":\"Redaktør\",\"coder\":\"Kildekode\",\"compact\":\"Kompakt\",\"new_file\":\"Ny fil\",\"project_archives\":\"Projektarkiver\",\"project_archives_tip\":\"Gem din json-streng for nem administration og hentning\",\"name_of_project\":\"Navn på projekt\",\"name_of_project_tip\":\"Navngiv det projekt, du vil gemme\",\"save_as_tip\":\"Arkiver dette projekt med et andet navn\",\"no_project\":\"Du har endnu ingen arkiverede projekter\",\"json_root\":\"Rodobjekt Json\",\"remove_ads_success\":\"Fjern annoncer med succes!\",\"project_name_error\":\"Projektnavnet må ikke være tomt!\",\"save_success\":\"Gem projektsucces!!!\",\"p_update_success\":\"Projektopdatering lykkedes!\",\"p_name_update_success\":\"Opdatering af projektnavn lykkedes!\",\"p_upload_success\":\"Succesfuld online projekthosting!\",\"share_project_tip\":\"Del dette json-projekt med andre\",\"import_file\":\"Importer fil\",\"import\":\"importere\",\"import_tip\":\"Importer json-data fra webadresse\",\"import_url_tip\":\"Indtast json web url\",\"import_url_error\":\"Input url må ikke være tom!\"}'),
('nl',	'{\"remove_ads\":\"Verwijder advertenties\",\"remove_ads_tip\":\"Koop geen in-app-advertenties\",\"setting\":\"Instelling\",\"help\":\"zelfstudie\",\"save\":\"Sparen\",\"app_sound\":\"Geluid\",\"app_sound_tip\":\"Zet het geluid in de app aan of uit\",\"delete_all_data_tip\":\"Verwijder de hele app, zet de app terug in de oorspronkelijke staat (inclusief gekochte items)\",\"in_app_restore\":\"Herstel aankoop\",\"in_app_restore_tip\":\"Functies en items herstellen die u eerder hebt gekocht\",\"open\":\"Open\",\"new\":\"Nieuw\",\"save_as\":\"Opslaan als...\",\"editor\":\"Editor\",\"coder\":\"Broncode\",\"compact\":\"Compact\",\"new_file\":\"Nieuw bestand\",\"project_archives\":\"Projectarchieven\",\"project_archives_tip\":\"Bewaar uw json-tekenreeks voor eenvoudig beheer en ophalen\",\"name_of_project\":\"Naam van het project\",\"name_of_project_tip\":\"Noem het project dat u wilt opslaan\",\"save_as_tip\":\"Archiveer dit project met een andere naam\",\"no_project\":\"Je hebt nog geen gearchiveerde projecten\",\"json_root\":\"Hoofdobject Json\",\"remove_ads_success\":\"Verwijder advertenties succesvol!\",\"project_name_error\":\"Projectnaam mag niet leeg zijn!\",\"save_success\":\"Projectsucces opslaan!!!\",\"p_update_success\":\"Projectupdate geslaagd!\",\"p_name_update_success\":\"Projectnaam update succesvol!\",\"p_upload_success\":\"Succesvolle online projecthosting!\",\"share_project_tip\":\"Deel dit json-project met anderen\",\"import_file\":\"Importeer bestand\",\"import\":\"importeren\",\"import_tip\":\"Importeer json-gegevens van webadres\",\"import_url_tip\":\"Voer json web-url in\",\"import_url_error\":\"Invoer-url mag niet leeg zijn!\"}'),
('pl',	'{\"remove_ads\":\"Usuń reklamy\",\"remove_ads_tip\":\"Kupuj bez reklam w aplikacji\",\"setting\":\"Ustawienie\",\"help\":\"Instruktaż\",\"save\":\"Zapisać\",\"app_sound\":\"Dźwięk\",\"app_sound_tip\":\"Włącz lub wyłącz dźwięk w aplikacji\",\"delete_all_data_tip\":\"Usuń całą aplikację, przywróć aplikację do pierwotnego stanu (w tym zakupione przedmioty)\",\"in_app_restore\":\"Przywróć zakup\",\"in_app_restore_tip\":\"Przywróć funkcje i przedmioty, które wcześniej kupiłeś\",\"open\":\"Otwarte\",\"new\":\"Nowy\",\"save_as\":\"Zapisz jako...\",\"editor\":\"Redaktor\",\"coder\":\"Kod źródłowy\",\"compact\":\"Kompaktowy\",\"new_file\":\"Nowy plik\",\"project_archives\":\"Archiwa projektu\",\"project_archives_tip\":\"Przechowuj swój ciąg json w celu łatwego zarządzania i wyszukiwania\",\"name_of_project\":\"Nazwa projektu\",\"name_of_project_tip\":\"Dê um nome ao projeto que deseja salvar\",\"save_as_tip\":\"Zarchiwizuj ten projekt pod inną nazwą\",\"no_project\":\"Nie masz jeszcze żadnych zarchiwizowanych projektów\",\"json_root\":\"Obiekt główny Json\",\"remove_ads_success\":\"Usuń reklamy pomyślnie!\",\"project_name_error\":\"Nazwa projektu nie może być pusta!\",\"save_success\":\"Zapisz sukces projektu!!!\",\"p_update_success\":\"Aktualizacja projektu powiodła się!\",\"p_name_update_success\":\"Aktualizacja nazwy projektu powiodła się!\",\"p_upload_success\":\"Udany hosting projektów online!\",\"share_project_tip\":\"Udostępnij ten projekt json innym\",\"import_file\":\"Importować plik\",\"import\":\"import\",\"import_tip\":\"Importuj dane json z adresu internetowego\",\"import_url_tip\":\"Wpisz adres internetowy json\",\"import_url_error\":\"Wejściowy adres URL nie może być pusty!\"}');

-- 2022-01-29 06:44:13
